### ISSUE TITLE
--tag doesn't parse port properly

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1030]
## Describe the bug
When the --tag flag references a registry that is hosted on a port, the port is being dropped when we parse the tag. 

## To Reproduce
1. Run `porter publish --tag localhost:5000/porter-hello:v0.2.0`

Note that porter tries to publish to `localhost/porter-hello:v0.2.0`

## Expected behavior
The full tag should be parsed properly.

## Version
Copy the output of `porter version` below

```
porter v0.26.2-beta.1 (e4aa6cd3)
```

**Comment by vdice** [comment]
I actually wasn't able to reproduce this issue when using a manifest with `invocationImage` defined (as `localhost:5000/porter-file-param-installer:0.1.0` for the below output):

```
 $ p version
porter v0.26.2-beta.1 (e4aa6cd3)

 $ p publish
Pushing CNAB invocation image...
The push refers to repository [localhost:5000/porter-file-param-installer]
...

Rewriting CNAB bundle.json...
Starting to copy image localhost:5000/porter-file-param-installer:0.1.0...
Completed image localhost:5000/porter-file-param-installer:0.1.0 copy
Bundle tag localhost:5000/porter-file-param:v0.1.0 pushed successfully, with digest "sha256:d0477843c7bfe171606a8e34c0e00e0bfb7be6de8b39778491af0628c2a62f70"

 $ p publish -t localhost:5000/porter-file-param:0.1.0
Pushing CNAB invocation image...
The push refers to repository [localhost:5000/porter-file-param-installer]
...
Rewriting CNAB bundle.json...
Starting to copy image localhost:5000/porter-file-param-installer:0.1.0...
Completed image localhost:5000/porter-file-param-installer:0.1.0 copy
Bundle tag localhost:5000/porter-file-param:0.1.0 pushed successfully, with digest "sha256:d0477843c7bfe171606a8e34c0e00e0bfb7be6de8b39778491af0628c2a62f70"
```

However, I did discover a bug in Porter's code around deriving the invocation image name when _not_ provided in a manifest (and when the tag registry is of the form `domain:port`).  The following PR is a proposed fix: https://github.com/deislabs/porter/pull/1033

**Comment by vdice** [comment]
@sajuptpm when/if convenient, can you assist in seeing if this bug still occurs off of the latest version of `master`?  A related fix has been merged and I'm not sure if another follow-up is needed.  Thank you!

**Comment by vdice** [comment]
Re-tested with the `porter` built from `master` (`porter v0.26.2-beta.1-11-gb22ec2bd (b22ec2bd)`) and am not reproducing this error.  Please feel free to re-open if others aren't seeing the same.
