### ISSUE TITLE
Porter Publish with Tag: Invocation Image not updated as well

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#1123]
## Describe the bug

It appears when invoking `porter publish --tag myotherreg/mybuns:v0.1.0`, although the bundle itself is published to `myotherreg/mybuns:v0.1.0`, the invocation image is still pushed according to the tag existing in the original bundle.  If the original tag is `myreg/mybuns:v0.1.0`, then the invocation image will be pushed to `myreg/mybuns-installer:v0.1.0` regardless of the value provided via `--tag`.

## To Reproduce
See `Porter Command and Output` below.

## Expected behavior

I'd expect the invocation image also to be published according to the provided tag value.  In the example above, I would expect `myotherreg/mybuns-installer.v0.1.0` to be published.

## Porter Command and Output
```
 $ # relevant section from porter.yaml:
 $ # tag: vdice/brigade:v0.1.0

 $ p publish --tag vdice.azurecr.io/brigade:v0.1.0
Pushing CNAB invocation image...
The push refers to repository [docker.io/vdice/brigade-installer]
a9c4c2c89016: Preparing
36dee3cbd658: Preparing
3edbb490cae5: Preparing
b12d7b0df04a: Preparing
a507cd767aeb: Preparing
4176e6eab4b0: Preparing
79412f56c979: Preparing
4ca11f8894f5: Preparing
dfd9baa45964: Preparing
6885f9305c0a: Preparing
4176e6eab4b0: Waiting
79412f56c979: Waiting
4ca11f8894f5: Waiting
dfd9baa45964: Waiting
6885f9305c0a: Waiting
36dee3cbd658: Layer already exists
b12d7b0df04a: Layer already exists
3edbb490cae5: Layer already exists
a9c4c2c89016: Layer already exists
a507cd767aeb: Layer already exists
4176e6eab4b0: Layer already exists
4ca11f8894f5: Layer already exists
6885f9305c0a: Layer already exists
79412f56c979: Layer already exists
dfd9baa45964: Layer already exists
v0.1.0: digest: sha256:306599cfc84cd4d874d734e1321db919f66739e81b991e03162db70a6cd351cf size: 2421

Rewriting CNAB bundle.json...
Starting to copy image vdice/brigade-installer:v0.1.0...
Completed image vdice/brigade-installer:v0.1.0 copy
Bundle tag vdice.azurecr.io/brigade:v0.1.0 pushed successfully, with digest "sha256:3d75c4abd4f6afcc8d3ae5cac3b7f622d628d369c76e012f41ac7da35631ce6a"
```

## Version
Copy the output of `porter version` below

`porter v0.27.0-11-gf7a551d2 (f7a551d2)`

**Comment by vdice** [comment]
@carolynvs I looked into fixing this and added code to update the invocation image being pushed during publishing to match the registry and docker tag if/when supplied via the `--tag` flag on `porter publish`.  However, pushing this updated invocation image fails as we haven't actually built the image locally -- so push bails out.  Should I proceed in the current direction and look into adding steps to build the image before attempting to push?

**Comment by vdice** [comment]
Here's the [branch](https://github.com/deislabs/porter/compare/main...vdice:feat/publish-update-inv-img?expand=1 ) adding logic to derive new invocation image name and build prior to pushing/publishing.  (It still needs unit tests and perhaps a bit of refactoring -- borrowed much of the image renaming logic from the `SetDefaults` method in `manifest.go`.)  WDYT?

**Comment by carolynvs** [comment]
I think that we can get the rebuild logic for free if we swap the tag check logic. Right now it's checking if the bundle is up-to-date **before** we decide if we need to rewrite the invocation image name used. We are invalidating the bundle immediately after that validation check that would have done the rebuild for us.

If you move your tag -> invocation image fixup logic before the call to `ensureLocalBundleIsUpToDate`, then you will get the rebuild and all the proper logic and testing "for free" on a single well tested code path that we share with all of the actions.

What do you think?

**Comment by vdice** [comment]
@carolynvs Great simplification!  Added; Thank you.

**Comment by carolynvs** [comment]
One more thought looking at the branch, at first glance it seems like there is a lot of overlapping logic between the new function and this existing one

https://github.com/deislabs/porter/blob/main/pkg/manifest/manifest.go#L539

Can we extract this function and reuse it between both places? So that if we need to make fixes we don't forget and only fix one?
