### ISSUE TITLE
Configure kubernetes mixin version

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1135]
**Is your feature request related to a problem? Please describe.**
K8s bumps their version every 3 months, we don't. 😀 

**Describe the solution you'd like**
I want to be able to specify the version of kubectl to build into the bundle just like we can with the helm mixin.

```yaml
mixins:
- kubernetes:
    clientVersion: v1.17.0
```

**Describe alternatives you've considered**
See #1136 for having the client version selected dynamically at runtime.

**Additional context**
Here is the [build code](https://github.com/deislabs/porter-helm/blob/main/pkg/helm/build.go) that helm uses to configure and download the specified version of helm.

**Comment by MChorfa** [comment]
@carolynvs I can help with this one
