### ISSUE TITLE
Syntax for documenting credentials with a specific value inside the porter.yaml

### ISSUE THREAD

**Issue by coreyperkins** [deislabs/porter#1139]
credentials:
  - name: CDP_CRED
  - value: ""

Credentials file:
{
  "name": "CFS",
  "created": "2020-07-15T09:08:45.72513-05:00",
  "modified": "2020-07-15T09:08:45.72513-05:00",
  "credentials": [
    {
      "name": "CFS_LICENSE",
      "source": {
        "value": "asdfasdf"
     }
   ]
} 

Is it possible to make this work? When I do porter install I get the following: Error: invalid bundle: validation failed for credential "CFS_LICENSE": credential env or path must be supplied

It doesn't seem to make sense that "env or path must be supplied" when obviously you can generate your credentials file with source/value.

Any help very appreciated!

**Comment by vdice** [comment]
Hi @coreyperkins,

The error returned is around the credential definition in the Porter manifest itself, which represents the credential _destination_ inside of the Docker image that executes the bundle, rather than the credential _source_ which is provided by the `CFS` credential set shown above.

Can you provide the `porter.yaml` manifest for this bundle (or at least the relevant `credentials:` section)?  The `CFS_LICENSE` credential needs either `env: TBD_ENV_VAR` or `path: /path/to/CFS_LICENSE_cred`.  As an example, check out the credentials section in the [Azure Wordpress example bundle](https://github.com/deislabs/porter/blob/main/examples/azure-wordpress/porter.yaml#L9-L19).

**Comment by coreyperkins** [comment]
@vdice I will send that as soon as I am back at my work station. I don't want to use an environment variable. I'd prefer to simply supply the credentials via the json file on Porter install. From what you are saying that doesn't sounds possible. If I must use a path to a file what would the contents of the file look like if this was only a single value, like a password?

**Comment by vdice** [comment]
Indeed, a destination of raw type 'value' could perhaps be handy.  It would be interesting to think about how that could work.

Porter at its core being an implementation of the CNAB Spec has the need to adhere to what the spec requires for [credentials](https://github.com/cnabio/cnab-spec/blob/master/101-bundle-json.md#credentials).  Hence, in this case, the requirement for either an env or a path value.  However, Porter also can drive updates to the spec, so with further thought, perhaps this is something we can look into.

In the meantime, indeed, all credentials, regardless of size, etc., need to be placed in the image that executes the bundle either in the form of an env var or a filepath.  Hope this helps!

**Comment by coreyperkins** [comment]
@vdice I agree. A raw type 'value' would be quite handy and relatively straight-forward.

Here's the credentials section: 

`{"credentials":{"CFS_LICENSE":{"env":"CFS_LICENSE","required":true},"OIDC_AUTHORITY":{"env":"OIDC_AUTHORITY","required":true},"OIDC_CLIENTID":{"env":"OIDC_CLIENTID","required":true},"OIDC_CLIENTSECRET":{"env":"OIDC_CLIENTSECRET","required":true},"kubeconfig":{"path":"/root/.kube/config","required":true}}`

I am having some minor questions to get passed to get my bundle functional.

1. Should the environment variables exist on the machine where the porter bundle is made? They do atm.
2. Should the environment variables exist on the machine where the porter bundle is installed? They do atm.

I have the credentials sections in the porter.yaml and in the bundle.json (above) when it is created.
I am also passing the following to the -c parameter on porter install

`{
    "name": "kubeconfig",
    "created": "2020-07-14T11:47:00.452976144-05:00",
    "modified": "2020-07-14T11:47:00.452976144-05:00",
    "credentials": [
        {
            "name": "kubeconfig",
            "source": {
                "path": "/home/$AdminUsername/.kube/config"
            }
        },            
        {
            "name": "OIDC_AUTHORITY",
            "source": {
                "env": "OIDC_AUTHORITY"
            }
        },            
        {
            "name": "OIDC_CLIENTID",
            "source": {
                "env": "OIDC_CLIENTID"
            }
        },            
        {
            "name": "OIDC_CLIENTSECRET",
            "source": {
                "env": "OIDC_CLIENTSECRET"
            }
        },            
        {
            "name": "CFS_LICENSE",
            "source": {
                "env": "CFS_LICENSE"
            }
        }
    ]
}`

When you say the credentials must be placed in the image that executes the bundle (the invocation image) that makes me think the environment variables need to exist on both the machine where I do the porter build and on the machine where I do the porter install. Is that correct?

Thank you for your help!

**Comment by vdice** [comment]
>I am having some minor questions to get passed to get my bundle functional.
>1. Should the environment variables exist on the machine where the porter bundle is made? They do atm.
>2. Should the environment variables exist on the machine where the porter bundle is installed? They do atm.

Good questions.  It again comes down to whether we're talking about the [Credential Set](https://porter.sh/credentials/) which is supplied to Porter at install/action runtime and designates the sources of the credentials (either via the local user's env/filesystem or hosted in a cloud store, such as Azure Key Vault by way of the [Azure plugin](https://porter.sh/plugins/azure/)) or whether we're talking about the credential destination definitions in the Porter manifest (and resulting `bundle.json` file).

For the former Credential Set sources, they must exist on the machine where the porter bundle is installed.  For the latter credential destinations, Porter handles creation of the destination env var (or file path) after parsing the Credential Set given to it on install.  And so, for the question:

> When you say the credentials must be placed in the image that executes the bundle (the invocation image) that makes me think the environment variables need to exist on both the machine where I do the porter build and on the machine where I do the porter install. Is that correct?

Porter handles placing the credential values in the image to the locations spec'd in the `porter.yaml`/`bundle.json` (e.g. `env` or `path`) after resolving each credential value from the supplied Credential Set.

The credential sources needn't exist on the user's machine where the bundle is being built, as they aren't injected at buildtime; rather, they are only injected at runtime (during `porter install/upgrade/uninstall/etc.`).

**Comment by vdice** [comment]
Great, I hope this helps you move forward!

Giving the raw value type for a credential destination some thought and I encountered a couple considerations.  Maybe you can help bounce some ideas around.

1. It's unclear how to supply the raw value to the runtime execution environment (classically this is a Docker container via Porter's (and CNAB's) default driver of Docker, but could be VM, Kubernetes, etc.).  How would the scripts/commands inside of the container access this value if not in the form of an env var or file?  (If you're curious, here's the go code where we [setup the env](https://github.com/cnabio/cnab-go/blob/master/driver/docker/docker.go#L190-L193) and [tar up the files](https://github.com/cnabio/cnab-go/blob/master/driver/docker/docker.go#L226-L229) prior to container start/run.)

2. Consider what the `porter.yaml`/`bundle.json` ends up looking like with credential destinations of `value` -- the value itself would be printed and leaked, right?  Presumably all credential values are sensitive, so this wouldn't be ideal.

**Comment by coreyperkins** [comment]
@vdice ... those are good considerations indeed. I would certainly not want to create a security concern. What if an encryption step was implemented on both ends to ensure the values could only be retrieved by the machine running the install?

**Comment by vdice** [comment]
Another angle to simplify/improve UX would be a Porter-specific piece of functionality wherein it would be okay for credential(s) in the Porter manifest to _not_ specify either `env` or `path`.  The value would then only be useful in the context of the manifest itself, via `{{ bundle.credentials.mycred }}` in install/upgrade/uninstall/etc. steps, and would either not be injected into the container at all (maybe behind the scenes Porter can just say `path: /dev/null` to appease the spec) or choose some default to inject it in the container (maybe `env: CREDNAME`).  Like I say, for creds that are only really intended to be used in the manifest via templating and not accessed via scripts/programs copied the container itself, perhaps this makes sense.

Users could would still supply `env` or `path` if they need to also access cred(s) via the application(s) running in the container itself, of course.

**Comment by carolynvs** [comment]
@coreyperkins I was hoping to follow up with you on this question

> What if an encryption step was implemented on both ends to ensure the values could only be retrieved by the machine running the install?

With plugins you can do that today, for example we have plugins to let you retrieve encrypted credentials from Azure Key Vault and Hashicorp Vault. Here's what that looks like:

1. You configure porter to use the plugin in ~/.porter/config.toml. For example:
```toml
default-secrets = "carolynvs"

[[secrets]]
  name = "carolynvs"
  plugin = "azure.keyvault"

  [secrets.config]
    vault = "carolynvs"
```
2. When you define a credential set, you can chose to lookup a credential from "secret", as opposed to "env" or some other location on the local host.
3. Now when you execute a bundle, porter will use the plugin to just-in-time to retrieve the encrypted secret from Key Vault or Vault, etc.
4. The decrypted value is injected into the bundle's executing docker container as either an environment variable or a file. The bundle is able to use the secret (either through porter's templating or by accessing the env var/file).
5. Porter removes the container when the bundle finishes executing.

Would that fit your requirements?

**Comment by coreyperkins** [comment]
@carolynvs Thank you so much for the response, sorry for my delay. I wasn't aware that the secrets plugin could also be used with hashicorp vault in addition to Azure, that is interesting. I do believe this would meeting my requirement and still keep the secret "stuff" secret. Thank you!

**Comment by carolynvs** [comment]
Yup! @dev-drprasad wrote a plugin to integrate Vault. You can find more info at https://github.com/dev-drprasad/porter-hashicorp-plugins
