### ISSUE TITLE
Update docs to not set the docker tag in the manifest bundle tag

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1146]
Our documentation has lines like this:

```
name: hello
version: 0.1.0
tag: getporter/porter-hello:v0.1.0
```

We now have a feature where the docker tag of the bundle automatically for you, including the v prefix. Let's encourage people to take advantage of this in our docs by updating them to look like this:

```
name: hello
version: 0.1.0
tag: getporter/porter-hello
```

Only update the documentation (*.md and porter.yaml files) in the following directories:

* /examples - the examples can be previewed in github only, or in a markdown editor
* /docs/content - See our contributing guide for how to [preview our website](https://github.com/deislabs/porter/blob/main/CONTRIBUTING.md#preview-documentation)
* /workshop - this can be previewed in github or in a markdown editor

**Comment by iennae** [comment]
all the documentation got updated with pull request #1173.
