### ISSUE TITLE
Provide a way to list available mixins

### ISSUE THREAD

**Issue by itowlson** [deislabs/porter#116]
It is often useful for tooling to know which mixins are present, for example to validate a `mixins` section in YAML or to query each mixin for its schema.  At the moment this requires tooling to locate the Porter binary and traverse subdirectories from there.  It would be useful to have a command such as `porter mixin list` to get the info from Porter itself.

**Comment by carolynvs** [comment]
What if porter helped get the schema too for the mixins?

so it would look like this?

```console
$ porter mixins list
helm
azure
exec

$ porter schema
dumps schema for porter.yaml

$  porter schema --mixin helm
dumps schema for the helm mixin
```

**Comment by itowlson** [comment]
~Are you trying to put me out of a job Carolyn?~

That would be great!  The implementation detail of mixin executables would then be entirely hidden - thanks!

**Comment by carolynvs** [comment]
Yeah requiring anyone to dig into the porter home directory and interrogate the binaries in there seems like we are failing people. 😀

**Comment by carolynvs** [comment]
Ok, I will merge what I have for the helm mixin and then stub out the rest of this flow in porter so that you can try out the entire idea in a single go.
