### ISSUE TITLE
Do we need a purge?

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1163]
After I've implemented keeping claims data after you run `porter uninstall`, there isn't a good way to uninstall a bundle then reinstall it with the same name and _start over_ without keeping all the old history (and maybe some buggy data that you were trying to get rid of).

Do we need a command to delete the data for an installation so that you can move on with your life? 😂

**Comment by vdice** [comment]
+1!  `porter kondo <installation name>` ?

**Comment by carolynvs** [comment]
No, this bundle does not bring me joy. 🔥

**Comment by vdice** [comment]
Perhaps a flag particular to `porter uninstall`?  Like `--force` or `--force-remove`, etc.?

**Comment by carolynvs** [comment]
I was thinking about that. Let's say that you uninstalled it without that flag weeks ago and now you want to cleanup the data. Running `porter uninstall --force` would perhaps give people incorrect expectations because we wouldn't execute uninstall again (or shouldn't?). We just want to remove the data from porter.

How about a primary command that removes porter data for a bundle, and a flag for uninstall that will call that command for you when you uninstall?

Scenario A - You were on the ball and knew that you wanted to remove everything when you uninstalled
```console
$ porter uninstall --delete wordpress
uninstall wordpress
delete all data for wordpress
```

Scenario B - You didn't realize you wanted to remove all the data until much later
```console
$ porter uninstall wordpress
uninstall wordpress

# weeks pass

$ porter installation delete wordpress
delete all data for wordpress
```

Scenario C - You have mightily screwed up the bundle and need to make it go away, you can't even get uninstall to work
```console
$ porter uninstall --delete wordpress
uninstall failed!
skipping tidy, it's not safe

$ porter installation delete wordpress --force
delete all data for wordpress
```

Alternatives for delete which may be a bad word that would be confused with uninstall:
* forget
* purge
* expunge

**Comment by vdice** [comment]
Thanks for providing the list of valid scenarios; very helpful.  I like it.  I don't have an issue with `delete`.  It seems to carry enough differentiating behavior from `uninstall`.  (`uninstall` to uninstall the bundle, though the installation record(s) shall remain; `delete` to delete all record(s) of the installation`.)

One follow-up Q: If `porter installation delete <installation>` is invoked on an installation whose last result action isn't `uninstall`, should it error out? Or call `uninstall` behind the scenes and proceed?  (Maybe the former if `--force` isn't included; maybe the latter if it is?)

**Comment by carolynvs** [comment]
I was thinking that by default the delete command needs to be safe and only remove records if the last command was uninstall and the uninstall was successful. Otherwise they need to use `porter installation delete --force`.

For `porter uninstall --delete` the --force flag already means something else, it means to force pull the tag if it was already cached. We use that flag for anything that supports --tag. I guess that's the problem with using a very generic word to modify another flag's behavior... Oops, we probably should have called it --repull or something that like. 

But for this case, maybe we have two flags on `porter uninstall`: --delete and --force-delete? --delete will be the safe flag it won't delete if the uninstall fails (giving you a chance to retry it). --force-delete will remove it no matter what.

**Comment by vdice** [comment]
I'll pull this in, working off of Carolyn's design mentioned in https://github.com/deislabs/porter/issues/1163#issuecomment-664531659 and https://github.com/deislabs/porter/issues/1163#issuecomment-664586962
