### ISSUE TITLE
Use Packr to put the templates into the porter binary

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#118]
Currently, Porter expects the templates/ directory to exist at a path relative to the binary or in PORTER_HOME. It would simplify things, including as new versions of Porter are released, if we used something like [packr v2](https://github.com/gobuffalo/packr/tree/master/v2) to bundle the templates into the binary. The ARM templates for the porter-azure mixin are handled this way for reference.

**Comment by carolynvs** [comment]
This is working great for both of the mixins, so I think investigation is closed. We just need to do the move at some point. 👍

**Comment by jeremyrickard** [comment]
I started a PR for this today.

**Comment by carolynvs** [comment]
I'm like 5 days late to the party, but yay! 🎉
