### ISSUE TITLE
Add dependency listing to porter explain

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#1197]
**Is your feature request related to a problem? Please describe.**
`porter explain` is a great way to see an overview of a bundle, showing bundle parameters, credentials, outputs, etc.

It would be nice to also see a listing of dependencies if the bundle being explained declares them.

**Describe the solution you'd like**
A listing of dependencies shown on `porter explain` when applicable

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by carolynvs** [comment]
I like it! 👍
