### ISSUE TITLE
Restore the ability to load parameters from a file-path 

### ISSUE THREAD

**Issue by CSberger** [deislabs/porter#1213]
### Problem
When we still had the `param-file` flag, our team got used to storing parameters for our various installations in parameter files in version control.  That way the parameters were transparent and easy to share between environments.  With the removal of the `param-file` flag, and the move to parameter-sets; we refer to parameters by name, and they're stored in the generating user's $HOME/.porter/parameters directory.

So in order to share a parameter-set file between developers, a user needs to add a step of copying the param-set file from one place to another. This is suboptimal UX.

### Solution
Add a `--param-set-file` flag to the install command which allows a user to specify the location of the parameter-set file by a file path; as existed before https://github.com/deislabs/porter/issues/1072, but using the new `param-set` syntax for the parameter file.

**Comment by vdice** [comment]
Hi @CSberger , `-p`/`--parameter-set` does currently accept a filepath as an argument, though be aware that it perhaps isn't ideal in the sense that it "auto-detects" whether or not the argument is a name or a filepath -- it looks for the presence of filepath separators for the latter case.

For example, if `myparameterset.json` exists in the current directory, one would need to supply it as: 

```
porter install -p ./myparameterset.json
```

Alternatively, the full/canonical path may also be used:

```
porter install -p /full/path/to/myparameterset.json
```

Does this address the needs you've mentioned?

**Comment by CSberger** [comment]
@vdice, The examples you provided were enough to help me figure out that my issue had indeed been with the parameter auto-detection syntax.

If I have a parameter file in my working directory, `testparams.json`, then apparently 
`porter upgrade -p testparams.json`
will interpret testparams.json as a name.  Whereas if I run
`porter upgrade -p ./testparams.json`
it will interpret that as a path,

and if I have testparams.json in a subdirectory (params) 
`porter upgrade -p params/testparams.json`
will interpret as a file path.

I think this autodetection behavior is a little surprising, but I'm satisfied that the functionality I was looking for still exists.  Thank you for the explanation.

**Comment by vdice** [comment]
Thank you @CSberger. I've created a follow-up issue to track improving the auto-detect logic especially as pertains the example you've provided above: https://github.com/deislabs/porter/issues/1217

I'll consider this issue closed.
