### ISSUE TITLE
Add Status action support

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#122]
Athough the CNAB spec currently only requires `install`, `uninstall` and `upgrade` actions to be implemented (https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-actions), it would be nice to support `status` actions as well.  

For instance, this action might show the status of helm releases installed by the porter-helm mixin, or perhaps show the state of resources in Azure via the porter-azure mixin.

However, since this represents an optional action (though perhaps the most common), we may consider this feature request too narrowly-scoped and instead create a wider-reaching ticket covering Porter's support of arbitrary optional actions.  Thoughts?

**Comment by carolynvs** [comment]
Would you mind filling in the issue description with a bit of background on what background/driver is for this issue is? It's not immediately clear from the title, and I wasn't aware of a CNAB action for status? Is that new?

**Comment by vdice** [comment]
Definitely, good call!  I've updated the description.  

Indeed, I've refreshed my spec knowledge and `status` is not a required action (looking at https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-actions).  I must have believed so from duffle's [implementation](https://github.com/deislabs/duffle/blob/master/pkg/action/status.go).

**Comment by carolynvs** [comment]
Note: The format of `status` has been changed to have a prefix of `io.cnab`. We don't want to expose that to the user however. One recommendation was that we automatically apply the `io.cnab.` prefix to custom actions when a dot prefix is not provided to a custom action (i.e. an action that isn't install/upgrade/uninstall).

**Comment by carolynvs** [comment]
This has been implemented with the invoke command.
