### ISSUE TITLE
Design: porter's cli api

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#129]
* `porter <NOUN> <VERB>` vs `<VERB> <NOUN>` vs total chaos
* common flags that we'll need for automation vs. humans, e.g. `-o json|table`
* what commands do we want to bring in from duffle
* Adding convenience commands like `helm upgrade --install` which is very scripting friendly

The output of this should the the full set of commands and flags we would like porter to support, and the guidelines for how new commands should look 'n feel.

EDIT: One of the goals of porter is to not require the user to know about CNAB or duffle. Which is why the CLI is wrapping commands already provided by duffle.

**Comment by carolynvs** [comment]
Notes:

# Wrapping duffle
1. Decide if we are wrapping everything from duffle, or a subset?
We don't want to exec to the duffle binary because we will want to read in the porter manifest (we don't have a duffle manifest). This also lets us change how the command is presented, as we may want to do some things differently, such as signing or the local store.
2. Are we keeping duffle's command word-for-word
Keep what duffle does to take advantage of muscle memory, unless we are trying to streamline a scenario. Then we may support a slightly different set of flags or have something defaulted.

# Local Store
* Porter will use the same file format / oci compliant format for local store so that the pkg in duffle can be given a path for duffle's store or porter's store and we can share the same code.
* local and remote store use the same format (carolyn finally understands)
* porter can look for dependencies in the local store under PORTER_HOME

# Grammar
We decided to optimize for the help text and understanding what someone can do with porter. So we grouped by nouns when possible. Not all of the commands fit this model now. I'll open issues later to adjust to match decisions made here. We may want to override the help text to group together actions and nouns.

```console
$ porter --help

## Things you can work with
* bundles
* credentials
* mixins

## Things you can do
init
install
upgrade
uninstall
status
```

# Command Groups
## Author Bundles
porter init
porter bundle create (are these build/create important enough to warrant aliases?)
porter bundle build

## Manage Credentials
porter credentials
* list
* add
* edit
* generate
* list
* remove
* show

## Manage local store
porter bundles
* list
* remove
* sign (not sure we want to have signing not paired with building)
* verify (need to write out the scenario for verifying a bundle not authored by the user)

Note: This kind of collides with bundle authoring.  Need to think about this more.

## Manage PKI (this may change soon in duffle, hold off)
porter keys
* export
* import
* list

Think about signing by default and how we can make this easier with porter (so people never have to deal with the pgp app), also public key verification.

## Manage mixins
porter mixin
* install
* upgrade
* uninstall
* schema

think about how to restore / install a set of mixins for a bundle authored on another computer

- [ ] Make sure we are consistent across commands with our verbs (remove vs uninstall)

**Comment by jdolitsky** [comment]
Would also like to see `porter bundle push`, `porter bundle pull`
