### ISSUE TITLE
Refactor: Extract shared exec mixin logic

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#142]
Per https://github.com/deislabs/porter/pull/135#discussion_r254037992 we should extract shared exec logic (basically, execute a script) into a sanely-named function that all of its actions (Install, Uninstall, Upgrade) can then use -- cuz exec gonna exec no matter what the action is!

**Comment by carolynvs** [comment]
Now that we have the pkg/exec/builder package, this is done.
