### ISSUE TITLE
Iterate on variable references

### ISSUE THREAD

**Issue by RomainMuller** [deislabs/porter#161]
As mentioned in #136, I feel like there is some interest in enabling composability in variable references. Instead of a strictly 1:1 mapping, I was suggesting using a format taking to how string interpolation is usually done:

```yaml
parameter.Name: |-
  jdbc:mysql://${outputs.hostname}:${outputs.port}/${outputs.dbName}
```

**Comment by jeremyrickard** [comment]
@RomainMuller check out the change here. Not 100% what you put up there, but similar. 

Using mustache templates now, feel free to throw darts at that and we can iterate some more.
