### ISSUE TITLE
Enhancement: porter run --file URL

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#174]
could `porter run --file` accept an URL as its input? (à la `docker build`)
This would allow, again like docker, to run with `porter.yaml` files stored on github (for example) and would allow testing, before building, without the need to download the said file or clone the repository.

Just an idea though, would totally understand if not applicable.

Thanks again for your work!

###EDIT
here is the workflow using a temporary file
![image](https://user-images.githubusercontent.com/905874/53025582-6dcaf380-3461-11e9-9a4d-215ab5253e86.png)

**Comment by carolynvs** [comment]
Good idea! Thanks I'll add that to the backlog

**Comment by youreddy** [comment]
Hey @carolynvs, I took a stab at this issue in PR https://github.com/deislabs/porter/pull/187. Let me know if you have any feedback. Happy to make changes to it!

**Comment by nunix** [comment]
You are simply Amazing 💯
