### ISSUE TITLE
Update CI to use a list of trusted committers

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#176]
Run the integration tests automatically on a PR for trusted committers.

**Comment by vdice** [comment]
@carolynvs As we haven't found a way to run all CI checks for trusted committers via Azure Pipelines, shall I/we work on porting what we currently have to a Brigade pipeline (with known mechanisms for running CI only for trusted committers)?  We have shared infrastructure already in place for other deislabs Brigade projects, so we're off to a great start -- and we have experience creating these pipelines on the team.  

Unless perhaps we were thinking of a different approach, with your go ahead, I can start work on this Brigade pipeline.

**Comment by carolynvs** [comment]
Oh yeah I was referring to moving to Brigade or Circle or something. I just didn't want to dictate how. 😀  Do what you gotta do so that we can run our integration tests again safely, please!

**Comment by radu-matei** [comment]
We :heart: Brigade!

**Comment by vdice** [comment]
Oh this can be closed; Brigade added a while back.
