### ISSUE TITLE
Add faq for minikube users to embed their certs

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#177]
We should put on a [faq](https://github.com/deislabs/porter/blob/master/docs/content/faq.md) page that if someone is using minikube that we recommend that they embed their certificates. Most of the examples will only include the kubeconfig but by default minikube puts the certs in a separate file.

They should run `minikube config set embed-certs true` (from [v0.29](https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md#version-0290---09272018)) so that minikube puts the certs in the config file. Otherwise you will get ugly error messages about being unable to connect.

```
err: couldn't get kubernetes client: couldn't build kubernetes config: invalid configuration: 
[unable to read client-cert /Users/carolynvs/.minikube/client.crt for minikube due to open /Users/carolynvs/.minikube/client.crt: 
no such file or directory, unable to read client-key /Users/carolynvs/.minikube/client.key for minikube due to open /Users/carolynvs/.minikube/client.key: 
no such file or directory, unable to read certificate-authority /Users/carolynvs/.minikube/ca.crt for minikube due to open /Users/carolynvs/.minikube/ca.crt: 
no such file or directory]
```

See the [Doc Contributing Guide](https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#documentation) for help on how to preview your changes.

**Comment by karencfv** [comment]
Hi! I can work on this 😄
