### ISSUE TITLE
validate all manifests in the repo

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#180]
We have manifests peppered through the repository, both as docs and testdata. They should be validated during the build so that changes to one particular part of the manifest don't accidentally end up not being made everywhere.

**Comment by vdice** [comment]
We think this is worth doing, b/c, as mentioned, manifest examples exist in many places and we have a need to keep them up to date.  Docs/markdown may be trickiest.

Added the 'hmm' label as this ticket still needs a bit of consideration on how to implement.

**Comment by carolynvs** [comment]
We are now validating all of our example bundles. All the testdata bundles get exercised through the tests so I think they are okay as-is for now.
