### ISSUE TITLE
Mixin in Windows (powershell) not compatible

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#188]
Hi team,

I have an (weird?) error after a fresh install of porter, via the powershell script described in https://porter.sh/install/

Porter version: 
porter v0.3.0-ralpha.1+caipirinha (66dad26)

Windows version:
Windows 10 insider 18342.19h1

![image](https://user-images.githubusercontent.com/905874/53426276-fa882b00-39e6-11e9-87dd-fdb5061ad1f5.png)

Actually, there's also the call itself from porter that looks for the mixin without ".exe" at the end and creates an error.
The workaround is to copy or rename the mixin without .exe

do I do anything wrong?

thanks a lot for the feedback
Nuno

**Comment by carolynvs** [comment]
This is a bug in porter's Windows install script.

When the `*-runtime` binaries are copied they shouldn't be given .exe file extensions, because they are compiled for linux amd64.

https://github.com/deislabs/porter/blob/66dad26f058ea0ae0607f329dbd9a392a9dc8619/scripts/install/install-windows.ps1#L18
https://github.com/deislabs/porter/blob/66dad26f058ea0ae0607f329dbd9a392a9dc8619/scripts/install/install-windows.ps1#L22
https://github.com/deislabs/porter/blob/66dad26f058ea0ae0607f329dbd9a392a9dc8619/scripts/install/install-windows.ps1#L26

**Comment by carolynvs** [comment]
@nunix Give https://deislabs.blob.core.windows.net/porter/canary/install-windows.ps1 a try and let me know if that helps, fixes it completely or not at all. 😀

**Comment by nunix** [comment]
thanks a lot for the fast bug fix and now, place to another one:
`Error: mixin execution failed: could not run mixin command C:\Users\nunix\.porter\mixins\exec\exec-runtime C:\Users\nunix\.porter\mixins\exec\exec-runtime install: exec: "C:\\Users\\nunix\\.porter\\mixins\\exec\\exec-runtime": file does not exist`

seems that the escape is not well taken in account, but I can be really wrong here.

**Comment by carolynvs** [comment]
How are you running porter this time around? I remember that previously you weren't running it inside of a CNAB environment. Has something changed that suddenly you are needing to use the runtime binaries? Those are only needed inside the CNAB invocation image (because it's linux).

**Comment by nunix** [comment]
Carolyn you are Gold 🥇 

so, until now I was running `porter run --action install --file ./porter.yaml` on WSL directly and the mixin `exec` was correctly calling the runtime.
I tried the same, on a VM, from Powershell directly (so no build before, directly run) and I have the errors stated in this case.

Now, thanks to your question and explanation on the script install that the runtime is actually linux and that I do (indeed) outside a CNAB environment, I finally understand the context and that I'm simply lucky that it work all together from the very beginning.

So please consider this issue as closed from my side too. I will be focusing more on a "real" CNAB environment after today :)

thanks again for the support, you rock 💯

**Comment by carolynvs** [comment]
Yay! I'm glad we figured it out. I would be up for your opening an issue explaining your goal, and we can work out the best way to execute porter. For example should you start with `porter run --action install`, use a CNAB environment (and how to set it up), etc and figure it all out in that issue.

**Comment by nunix** [comment]
will do it for sure, after the demo, see potentially the ideas or advices that I could eventually get to make it more "CNAB" oriented.

Thanks again for the support, really appreciated
