### ISSUE TITLE
Support concurrent CI runs of integration tests

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#215]
Currently, multiple runs of the integration tests (see the `test-cli` make target) may conflict, causing failures.  For instance, the `porter-wordpress` example bundle installs a helm chart onto a shared k8s cluster and the helm release name is currently not unique.

The work for this ticket therefore is to ensure multiple/concurrent CI runs are supported.

**Comment by carolynvs** [comment]
If we generate a random namespace is this enough? I think it is. Ideas on how to do that easily in helm? @vdice ?

**Comment by carolynvs** [comment]
Hmm actually we probably want to generate this info from the makefile/bash so it's the same for the entire test run, not in the helm chart for just the single bundle being installed, so that won't work. I'll try to get this fixed today, as Jeremy and I are playing dueling CI Tests.
