### ISSUE TITLE
porter build should always create secure bundles

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#224]

**Comment by carolynvs** [comment]
Hold off on this for a bit while CNAB/duffle redoes how it handles signing.

**Comment by jeremyrickard** [comment]
This seems to still be unsettled in CNAB/duffle..maybe we flip install to assume unsigned for now? Experience will be a little easier until it's all settled.

**Comment by carolynvs** [comment]
Yeah I hate always having to use `--insecure` when it's the only thing that works right now. EXECUTE! 👍

**Comment by carolynvs** [comment]
Closing as the security spec is not complete.
