### ISSUE TITLE
Enhance pkg/test to support multiple mock commands

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#231]
Currently, the testing helper in pkg/test has a `TestMainWithMockedCommandHandlers` function that works with an expected and actual command that will run. However, it doesn't support cases where a single unit under test might produce multiple commands. We should think about how to enhance this to more generically support multiple expected commands.

**Comment by carolynvs** [comment]
Off the top of my head, would `\n` to separate multiple commands work?
