### ISSUE TITLE
Add terraform mixin to our integration tests

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#253]
Now that we have a terraform mixin, it should be exercised as part of our integration suite (make test-cli).

Not sure yet what it should be used to install yet, but ideally something that we install as part of the kubecon eu demo.

**Comment by vdice** [comment]
A minimal/local integration test as part of CI is added in https://github.com/deislabs/porter/pull/261

I'm also planning on creating a less trivial bundle, which we can place in `examples` if we wish.  Perhaps creating an Azure resource (AKS cluster, ACR, other?)

**Comment by carolynvs** [comment]
Yeah a more exciting bundle for the examples is a great idea. 👍
