### ISSUE TITLE
Porter `init` should setup porter environment 

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#28]
`porter` should have a command like `init` that sets up your "Porter Home" with cross compiled binaries for `porter` and the `mixins` to support building invocation images. 

For example, I download the Windows `porter` binary. `porter init` should create a directory structure under %HOME%/.porter/ and %HOME%/.porter/mixins with appropriate cross platform binaries. These will be used to populate the Docker invocation images when created.

**Comment by carolynvs** [comment]
Closing because we don't plan on having an explicit porter init command anymore. When porter runs and detects that the current state isn't correct, for example a directory should be created, a runtime binary downloaded, or a key generated, it should take the proper healing action.
