### ISSUE TITLE
Suggestion: Don't require mixins to be declared

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#317]
Right now we require that all mixins are declared "up-front"

```yaml
mixins:
-helm

install:
- helm:
    ...
```

But since they used it in the install step later, we can easily figure out that it was being used. It would be better to not hard fail when they use a mixin without declaring it. It's super annoying that porter knows enough that we are using a mixin to warn us, but can't just figure it out and move on. 😀 

Once porter can install and use mixins based on the mixins declared in the manifest, people will have an incentive to declare mixins (with the version and potentially source). But if the user doesn't have a preference, it should be okay to use it and not declare a version.

My one concern/question on this is what the impact would be to the json schema for porter. The declared mixins drive the allowed schema for subdocuments. So we'd either have to be a lot looser on validation, backfill for them, or something else. I don't want to allow the json schema to dictate how people can use porter though.

**Comment by jeremyrickard** [comment]
I kind of like having the mixins declared at the top of the manifest because it makes it really apparent what functionality (mixins) will be used. It's not really much harder to go scan through manifest to see what is happening, but in the case of a complicated Porter bundle (should we think of a different name?), having them declared makes it super apparent what will be used (and what won't..that last one goes away if we make it optional and not everything is declared).

**Comment by carolynvs** [comment]
I suggest "Heroic Porter Bundle", and picture a cape flowing in the breeze behind the author.

This isn't a "we must do this", just something to think about and see if we like or not. Let me clarify on the title. Or we can close now. The schema problem, plus your initial no is kind of a deal breaker for me.

**Comment by vdice** [comment]
As a potential additional argument in favor of keeping the explicit `mixins` section, if we still anticipate scenarios where mixin-level configuration would be supported (say, mixin version/uri or perhaps configuration to by used by the mixin itself), then this would probably be the natural spot to put such items.

**Comment by carolynvs** [comment]
Closing as a rejected suggestion.
