### ISSUE TITLE
[Spec]: Support CNAB Bundle Outputs

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#344]
Now that the CNAB spec now supports bundle outputs, Porter should support bundle outputs.

This involves: 
* Allowing Porter users to define the outputs produced by the Porter bundle
* Updating the Porter runtime orchestrator to produce these in the specified location
* Updating the Porter cli to access outputs.

**Comment by vdice** [comment]
> Updating the Porter cli to access outputs.

What do we envision this looking like?  Let me know if the following sounds good:

Top-level `porter bundle outputs` and/or `porter outputs`?  If the former:

- `porter bundle outputs list [BUNDLE NAME]`: list outputs for a given bundle (could be `show`?)

Actually, perhaps the one `list`/`show` command is all we need/want right now?

**Comment by vdice** [comment]
Closed by https://github.com/deislabs/porter/pull/438
