### ISSUE TITLE
[Funny bug]: Porter build adds cnab copy everytime

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#355]
As the title says, this is a funny bug 😄 
If a `porter.yaml` has the `dockerfile` set, then everytime we do a `porter build`, it will had a new instance for copying the `cnab` directory into the `dockerfile`:
![image](https://user-images.githubusercontent.com/905874/58234084-05303300-7d3e-11e9-9561-7133ac1bfd9b.png)

I suddenly ended with 5 additional layers to my docker image and didn't understand why 😅 

Hope this helps

**Comment by jeremyrickard** [comment]
@vdice it is! We took a look at this with Nuno and that was the case. I opened an issue to clarify that in the docs and add error handling.

**Comment by nunix** [comment]
hi Team, indeed, I did change the name now and everything works as intended. My bad 😅 

Should I close this issue now? (for me it's closed)

Thanks a lot for the prompt, on-site support Jeremy ⭐️
