### ISSUE TITLE
porter credentials show

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#371]
```
$ porter credentials show NAME [-o table|json|yaml]
Name: Azure-Production

Credential Mappings
====================================================================
Name                Local Source                    Source Type
--------------------------------------------------------------------
CLIENT_ID           AZURE_CLIENT_ID                 Environment Variable
CLIENT_SECRET       AZURE_CLIENT_SECRET             Environment Variable
SUBSCRIPTION_ID     AZURE_SUBSCRIPTION_ID           Environment Variable
TENANT_ID           AZURE_TENANT_ID                 Environment Variable
kubeconfig          /Users/carolynvs/.kube/config   File
```

We may want to look at using a table writing package. I recommend starting with https://github.com/Landoop/tableprinter and falling back to https://github.com/olekukonko/tablewriter. My attempts and making a table above are sad, feel free to make something prettier or use the defaults from those packages. I was looking for something that put a line under the headers and didn't put lines between the columns.

**Comment by vdice** [comment]
This would take a required argument (credential name), correct?  E.g., `$ porter credentials show CREDENTIAL_NAME [-o table|json|yaml]`

Or, would we want the credential name arg to be optional and `$ porter credentials show` sans any arg shows all creds?  (If so, would this replace the `credentials list` ticket in https://github.com/deislabs/porter/issues/366 ?

**Comment by carolynvs** [comment]
Oops! You're right, it needs a `NAME` argument. Just updated the OP to reflect that. 😊

**Comment by vdice** [comment]
Completed with https://github.com/deislabs/porter/pull/375
