### ISSUE TITLE
Make invocation image optional in Porter Manifest

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#383]
Now that we are going to require a `tag` attribute in the porter manifest for the bundle publishing, we should be able to derive the invocation image name from the bundle. Invocation image is really a CNAB concept and if we don't require it, the experience will likely be enhanced. 

We should allow it to be specified, however, for people who wish to do so.

**Comment by carolynvs** [comment]
Add a function to Manifest, maybe `SetDefaults`?, and call it after we [load the manifest from the filesystem](https://github.com/deislabs/porter/blob/b24cdd412147c8156942f6d8accb489e71e48e6f/pkg/config/manifest.go#L370). Check if the invocationImage is empty, and default it to `tag`-installer.

So if `manifest.Tag` is "deislabs/porter-hello:latest", then `manifest.InvocationImage` should be defaulted to "deislabs/porter-hello-installer:latest".

Make sure to document how we default this value in https://github.com/deislabs/porter/blob/master/docs/content/authoring-bundles.md

**Comment by phillipahereza** [comment]
@jeremyrickard does the version tag of the invocationImage default to the version tag of `manifest.Tag` or the `manifest.Version` or just `latest`
