### ISSUE TITLE
Update CI to publish examples

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#396]
Now that we can publish stuff, it might be cool if we update the CI to `porter build` and `porter publish` the examples when they change. 

People can also try things out with `porter install --tag <stuff>` calls instead of cloning the repo.

**Comment by carolynvs** [comment]
I updated your title to remove the ? because we should totally do this. 🔨

**Comment by vdice** [comment]
Implemented in https://github.com/deislabs/porter/pull/417
