### ISSUE TITLE
Update CI to use dind approach for jobs needing daemon access

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#409]
Some CI jobs/tasks require access to a Docker daemon.  As of today, they access the K8s node/host daemon.  We should revisit and pursue a Docker-in-Docker approach (as opposed to this Docker-on-Docker approach, which is usually regarded as less favorable).

Example: https://github.com/brigadecore/brigade/blob/master/brigade.js#L52-L67 courtesy @krancour 

Note: We may need look for/produce an image with the add'l various tools these targets rely on -- golang, az -- in addition to the dind setup.

**Comment by krancour** [comment]
> Note: We may need look for/produce an image with the add'l various tools these targets rely on -- golang, az -- in addition to the dind setup.

Generally (on other projects) we have not had to do this. Let's put our heads together tomorrow.

**Comment by vdice** [comment]
Completed with https://github.com/deislabs/porter/pull/421
