### ISSUE TITLE
Support custom actions

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#413]
We should support custom actions. We need to consider what this experience might look like. Maybe:

> porter invoke —action <action-name> (other args like install).

Porter would need to validate that the specific action is in the bundle and handle errors when mixins used by the bundle don’t support said mixin.

**Comment by carolynvs** [comment]
Thinking about the other actions, they are all rooted on the bundle resource:

```
porter bundle install
porter bundle upgrade
porter bundle uninstall
```

Then we have aliases to make it easier for people to get to it

```
porter install
porter upgrade
porter uninstall
```

Some of the things we are worried about are:

* That the porter cli can detect that it's a real command (and not a typo), which makes it tempting to make it a flag or positional argument and not a subcommand.
* That the custom action is defined in the bundle
* That every mixin used in the custom action support the custom action or it's a mixin that doesn't need to support the action (or example exec supports any action). Right now we don't have a way in porter to ask a mixin "do you support this action?"
* Ensuring that schema validation doesn't fail against a manifest that does use a custom action, i.e. the exec mixin for example shouldn't be so strict that it reports an error when used in a custom action.

**Comment by jeremyrickard** [comment]
I think the custom actions have to be a flag off a different subcommand:

```
porter bundle invoke --action <INSTALL> 
```

This could be a regular install command and we can leave the existing commands for install. New custom actions could be: 

```
porter bundle invoke --action <CRAZY_TRAIN>
```

For the "built-in" commands, we could default to the existing things. For the custom actions, we could first check that:

> That the custom action is defined in the bundle

I think we can handle checking that pretty easily?

> That every mixin used in the custom action support the custom action or it's a mixin that doesn't need to support the action (or example exec supports any action). Right now we don't have a way in porter to ask a mixin "do you support this action?"

We should probably add something to the mixin interface/contract that satisfies this

> Ensuring that schema validation doesn't fail against a manifest that does use a custom action, i.e. the exec mixin for example shouldn't be so strict that it reports an error when used in a custom action.

This will be some craaaaazy JSON Schema, but it's probably possible with JSON Schema. 

The alternative is that we don't support that part of the spec. I believe that it's optional, so we _could_ just not implement it. 

This is probably not a super near term thing, I think figuring out how the mixins / porter will support the image map (which is a required part of the spec) takes higher priority imo.

**Comment by carolynvs** [comment]
nooooooo I just lost all my github comment.... 😭

**Comment by carolynvs** [comment]
> This will be some craaaaazy JSON Schema, but it's probably possible with JSON Schema.

when in doubt just keep it * 😀

**Comment by carolynvs** [comment]
> I think we can handle checking that pretty easily?

Sorry I was using the term "worried" to mean, "If you pick up this user story, please look out for this stuff". I didn't mean it was an unsolvable problem. 😀

**Comment by carolynvs** [comment]
porter bundle invoke --action <INSTALL>  👍

**Comment by nunix** [comment]
Hi team,

after sending it to Carolyn, I'm also sharing my user 2cents here 😄 

instead of creating custom actions, what if we would use aliases to specific mixin calls within the upgrade action?

in "my latest test", instead of emulating the different actions, I would have a specific call to start and stop
```yaml
upgrade:
  - exec:
      description: "check the cluster status"
      alias: stop
      command: bash
      arguments:
        - -c
        - "server stop --name {{ bundle.parameters.servername }}"
```

hope this makes sense and I discarded the `install` and `uninstall` actions as it's normally only done once.

BR
SwissPorter 😈
