### ISSUE TITLE
Do we want to bump Porter's default (golang) base invocation image?

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#416]
Currently, Porter uses `quay.io/deis/lightweight-docker-go:v0.2.0` as the default (golang) base invocation image for bundles.  This particular image has published newer [tags](https://github.com/deis/lightweight-docker-go/tags), perhaps with no added features that Porter really needs, other than a more recent version of golang.

**Comment by jeremyrickard** [comment]
We're actually only using that as part of the multi-stage build to add root SSL certificates. We could probably do that another way and remove the use of that entirely?

**Comment by vdice** [comment]
Ah, good point.  Yup, no real need to bump version then...

**Comment by carolynvs** [comment]
It would be nice to install the root ssl certs in a way that people recognize more clearly instead of copying from that image. However realistically it's pretty low on the list of things we need to do.

Y'all mind if I close?

**Comment by vdice** [comment]
Yea, agreed on low priority, with the clarification provided above.  Closing.
