### ISSUE TITLE
[Possible BUG] porter.yaml not copied when dependency exists

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#422]
hi team,

I'm trying (really) hard to get my first package to work with a dependency.
The dependency is located in ./myBundle/bundles/myDependency/porter.yaml:

![image](https://user-images.githubusercontent.com/905874/59621437-991fcf80-912f-11e9-9a4b-f9b56903d442.png)

after a `porter build` here is the result:
![image](https://user-images.githubusercontent.com/905874/59621558-de440180-912f-11e9-8e02-2e1814616cab.png)

Am I doing something wrong?

[EDIT] I just tried to move the dependency to `%HOME/.porter/bundles` and I do have the same result
![image](https://user-images.githubusercontent.com/905874/59622273-64ad1300-9131-11e9-9bd5-ecea204973e2.png)

SwissPorter 😄

**Comment by carolynvs** [comment]
As a workaround, please try removing completely the bundles directory next to porter.yaml and put dependencies in ~/.porter/bundles. There is a bug in porter where `porter build` fails if there is a bundles directory next to porter.yaml and the build will abort.

It looks a bit like this when it happens:
```
$ porter build -v
...
mv: inter-device move failed: '/cnab/app/cnab/app/bundles' to '/cnab/app/bundles'; unable to remove target: Directory not empty
Error: unable to build CNAB invocation image: failed to stream docker build output: The command '/bin/sh -c mv /cnab/app/cnab/app/* /cnab/app && rm -r /cnab/app/cnab' returned a non-zero code: 1
```

After making sure the bundles directory wasn't next to porter.yaml, and moving it to ~/.porter/bundles instead, I reran `porter build` and was able to get the bundle to build successfully. So I hope it will work for you too!

We are going to redo dependencies entirely within the month so hopefully the workaround helps for now.

If you are still seeing something different when using the workaround, can you post the full verbose output, or provide a link to something that I can use to reproduce?

**Comment by nunix** [comment]
thanks a lot for the prompt feedback Carolyn 😄 
as written in my [EDIT], I already tried to move the dependency to the `~/.porter/bundles` directory and here is the output:

```yaml
porter build -v
Copying dependencies ===>
Copying bundle dependency cnabk3d ===>
Copying porter runtime ===>
Copying mixins ===>
Copying mixin exec ===>

Generating Dockerfile =======>
FROM alpine:latest as BUILDER
RUN apk add -u wget
WORKDIR /tmp
RUN wget https://get.helm.sh/helm-v3.0.0-alpha.1-linux-amd64.tar.gz
RUN tar -xvzf helm-v3.0.0-alpha.1-linux-amd64.tar.gz

FROM docker:19.03.0-rc2-dind
RUN apk add -u bash curl
### Install K3d
RUN curl -s https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash
### Install Helm3
COPY --from=BUILDER /tmp/linux-amd64/helm /usr/bin
### Creates the .kube directory
RUN mkdir /root/.kube

ENTRYPOINT ["/bin/bash"]
# exec mixin has no buildtime dependencies

COPY cnab/ /cnab/
COPY porter.yaml /cnab/app/porter.yaml
WORKDIR /cnab/app
CMD ["/cnab/app/run"]
```

but looking further, I started a container from the image generated and I could see my `porter.yaml` correctly copied.
So this is more a "visual bug" in the end, with the `porter.yaml` not copied to `cnab/app` in the filesystem itself (hope it makes sense).

Anyway, I got it working, so I'm very pleased to say that I have a "full options" bundle :eyes

**Comment by carolynvs** [comment]
Oh! Just to make sure that I understand, let me summarize. You were expecting that on your local file system (not on the bundle's file system in the container) that the generated cnab/app/ directory would contain porter.yaml?

**Comment by nunix** [comment]
actually, and I might really wrong here, I did expect seeing the `cnab` directory to be the same as "uploaded" in the container indeed.
By not seeing the `porter.yaml` in it, I also thought it was not done inside the container.

My thought process about the `porter build` was/is:
- creates `cnab/app/mixins/` directories
- creates and copies the mixins in `cnab/app/mixins/<mixin declared in porter.yaml>` directory
- creates and copies the dependencies in `cnab/app/bundles`
- generates and copy the `bundle.json` file in `cnab/`
- copies `porter.yaml` in `cnab/`

this last step is the one I don't see in the filesystem, however it exists in the container. That's why it was a bit unclear for me if it was doing the job or not

**Comment by carolynvs** [comment]
Thanks that helps! We put some files into it to stage things before copying them into the bundle, but depending on what we need to copy, we may not need to put the files into that directory first. 

The cnab directory on your local filesystem isn't meant to be a 1:1 replica of what is in the bundle. I am trying to figure out how make it go away entirely so that it isn't visible to the user at all actually. Ideally the cnab directory would be immediately deleted after build finishes so that you wouldn't see it at all, and maybe we would make it a hidden directory during build so that it isn't so visible too. 🤔 

Good to know what it looks like from the user's perspective though.

**Comment by carolynvs** [comment]
Is it okay to close this since you have a workaround?

**Comment by nunix** [comment]
sorry, yes totally 😄 
I don't want to confuse new persons neither haha.

Once again, thanks a lot for your time and explanations ⭐️

**Comment by carolynvs** [comment]
No worries! and hopefully we will have the better dependencies for you soon!

**Comment by nunix** [comment]
just one last point, still related to the "perception":
it could be nice to explain the dependencies+main bundle run orders.

While it might be "logic", it could nice to have a sort of diagram or just few steps.
For me, based on the tests, I would say it ran as follow:

- `install`: Dependency > Main bundle
- `upgrade`: Dependency > Main bundle
- `uninstall`: Main bundle > dependency

Finally, this means that it was not possible to run `upgrade` of the main bundle or the dependency "alone".

Of course, if not intended to do so, please disregard this last sentence 😅
