### ISSUE TITLE
Update Parameters struct to support CNAB 1.0 changes

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#439]
In addition to the schema elements in a bundle.json, a Porter user should be able to use the "applyTo" specification to say that a parameter applies to only certain cnab actions, upgrade and uninstall, for example.

**Comment by carolynvs** [comment]
I just ran into this during uninstall. When no parameters are specified vs. any parameters specified, this triggers different logic in duffle to validate parameters. When a parameter is required, right now it's required for all actions (including uninstall). So once you specify a parameter, like --debug, this triggers other required parameters to be enforced when previously they were not. Which is sketchy logic all by itself...

Having applyTo would let us define a required parameter and have it only apply to install, not uninstall.

**Comment by vdice** [comment]
We may want to update this ticket to also add support for the `Immutable` (bool) field part of the Parameters spec as well (if we aren't already tracking.)

I'm working on fixing https://github.com/deislabs/porter/issues/449 (and adding in missing Credentials and Parameters sections) but will omit `ApplyTo` (and `Immutable`) from Parameters until implemented (in this ticket).

**Comment by vdice** [comment]
Created https://github.com/deislabs/porter/pull/476 to address this issue -- left out implementing `Immutable` as it seems there is momentum to remove from the spec prior to 1.0
