### ISSUE TITLE
Update Porter's Schema per CNAB Spec 1.0

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#444]
Porter's [Schema](https://github.com/deislabs/porter/blob/c3908ac973a71c9f710a13f8dcbbe016758e8bd6/pkg/config/manifest.go#L62-L73) struct needs to be updated to allow for full json schema support per CNAB Spec 1.0 (See https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#definitions)

**Comment by carolynvs** [comment]
Closing now that #504 is merged
