### ISSUE TITLE
feature: Make file parameters an easy mode thing in Porter

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#480]
There have been a number of questions regarding "how do i pass a file as a parameter" from people such as @squillace. Porter doesn't _explicitly_ improve that experience at the moment. To handle this currently, you'd need to have a `string` type parameter defined for the bundle. Then, you'd need to base64 encode the file, and provide that as the param when using Porter. Inside the invocation image, you'd probably need to use the `exec` mixin to base 64 decode that parameter and shove it in a file. All of that is pretty messy and annoying. What if Porter could help?

Two small user stories to complete with this feature:

1.) As a user, I want to declare that my bundle needs a `file` parameter and have that parameter placed in a file in the invocation image's file system. The resulting `bundle.json` should end up with a Parameter definition of type `string` and a `content-encoding` of type base64. When the bundle is invoked and the base64 encoded file is passed as a parameter, Porter should decode it automagically into a new file on the file system for me.

1.) As a user of Porter, I want to specify a _file_ on the file system and have that passed into the invocation image as a  base64 encoded parameter. Porter should read the file, base64 encode it and pass it to the invocation image. It would be nice if Porter could warn me that there is no `content-encoding` present on the parameter definition, but this probably(or maybe it should??) result in an error.

**Comment by carolynvs** [comment]
So for #1 the workflow could look like this?

```yaml
parameters:
  - name: kubeconfig
     type: file
     default: {{ porter.build.env.home }}/.kube/config
```

Then the user could change the default when they install the bundle 

```console
$ porter install --param kubeconfig=/tmp/aks-config
```

In either case porter would handle during install detecting the a parameter is a file, retrieving the contents and base64 encoding the contents before inserting that value as the parameter.

**Comment by carolynvs** [comment]
For #2, can we automatically apply a content encoding of base64 if one isn't present? Or is that not a safe thing for Porter to default?

**Comment by carolynvs** [comment]
I recommend doing everything but the `default: "{{ porter.build.env.home }}/.kube/config"` part first, then we can add that in a later step.

**Comment by jeremyrickard** [comment]
Leaving the default part til last sound good. How would that specific example end up working? {{ porter.build.env.home }} as a specific example would be specific to the bundle author wouldn’t it? Am I reading too much into that example?

**Comment by carolynvs** [comment]
Oh yeah! You're right using `porter.build.env.home` for that one would be a bad default. But we could make up a new one like `porter.env.home` instead to have porter grab an environment variable dynamically. 

This is why I was suggesting that we do the feature in 2 parts. There are neat things we can do to enable the use case that I think people will want: "default to grabbing my kubeconfig out of my home directory" but it will rely on some extra feature work first.

**Comment by carolynvs** [comment]
Closing for now as we have everything implemented except my half baked suggestion for defaulting using a feature we don't have (and that is represented in other issues).
