### ISSUE TITLE
Porter Publish for Thick Bundles / Archives

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#545]
CNAB thick bundles are used for transmitting across air-gapped networks. Duffle currently has some import/export capabilities, and I think we should add these in Porter as well. This issue tackles the import side of the equation.

In Duffle's case, the `import`brings the bundle into the local bundle cache. Porter doesn't really have that concept, and instead works from a directory with a porter.yaml, a tag, or a cnab file. 

For importing with Porter, I propose that our imports always publish to a registry, similar to what would happen with a `porter publish`. The `porter publish` of a bundle is the logical conclusion of a development cycle for a bundle. The invocation image, along with any referenced images, end up in a registry, along with the bundle metadata in the form of a bundle.json. In _most_ cases where a thick bundle containing other images will be used, those will _likely_ need to end up in a registry somewhere...not just a local docker daemon's cache of images. So our `import` can fulfill this need by essentially rehydrating the bundle into a registry. Then people can use it like a thin bundle, that is just based in the new registry. 

The UX might look something like: 

```
$ porter import -f <path-to-thick-bundle> myrepo/my-cool-bundle:0.1.0
```

This should load the tgz file, publish the invocation image and any referenced images to the "myrepo" registry with appropriate names from the bundle and finally update the bundle.json to reference these and publish the bundle.json to the specified tag, just like a `porter publish`.

**Comment by carolynvs** [comment]
Sounds great, though I would like to see us do this instead:

```
porter publish --thick-bundle /tmp/mybuns.tgz myrepo/my-buns:0.1.0
```

The **import** verb by itself doesn't explain well what is going to happen when you run the command. But after reading the steps you outlined, this sounds like a perfect fit for the publish verb we have already. Publish in porter already means "we will do all the steps necessary to prepare a bundle for distribution and then publish it to a registry".

What do you think?

**Comment by carolynvs** [comment]
Not sure the flag should really be `--thick-bundle`, but I wanted to see what you thought about using the `publish` verb.

**Comment by vdice** [comment]
We have publishing from an archive today, albeit with the effect of writing a new bundle.

The next logical step would be to build off of the relocation mapping support/wiring recently done by @jeremyrickard and utilize this to push the same/original bundle to the new bundle tag _after_ we push the updated images directly from the archived OCI Layout.  In essence, we wish to maintain the offline/air-gapped functionality we currently have (can publish from an archive w/o access to original image registry) but maintain the content digest of the original bundle for signing/security guarantees (basically, don't create/write a new bundle to the given tag, but use what cnab-to-oci and forthcoming signing functionality offers).

**Comment by vdice** [comment]
Created https://github.com/deislabs/porter/issues/739 to track the work mentioned above.  We can close this ticket.
