### ISSUE TITLE
Easy Way to Test New Mixin with Porter

### ISSUE THREAD

**Issue by donmstewart** [deislabs/porter#548]
Is there an easy way to locally test a new Mixin without publishing it to a public URL first?

I have the skeleton of the Mixin partially working but need to test it via Porter to ensure it is working.

So I wondered if there is a local install option or some other way...

**Comment by carolynvs** [comment]
The porter binary doesn't have a command to help with that but here is what I have been doing in my Makefile:

```makefile
install:
	mkdir -p $(PORTER_HOME)/mixins/$(MIXIN)
	install $(BINDIR)/$(MIXIN)$(FILE_EXT) $(PORTER_HOME)/mixins/$(MIXIN)/$(MIXIN)$(FILE_EXT)
	install $(BINDIR)/$(MIXIN)-runtime$(FILE_EXT) $(PORTER_HOME)/mixins/$(MIXIN)/$(MIXIN)-runtime$(FILE_EXT)
```
https://github.com/deislabs/porter-gcloud/blob/a1f902d3094db7607b8128a6c01c95605d7d3b9c/Makefile#L107-L110

This is a snippet from the gcloud mixin but if you look at the Makefile from the other mixins (helm, terraform, aws, etc) they all do something similar.

So the workflow would be this:

```console
$ make build install

mkdir -p /Users/carolynvs/.porter/mixins/gcloud
install bin/mixins/gcloud/gcloud /Users/carolynvs/.porter/mixins/gcloud/gcloud
install bin/mixins/gcloud/gcloud-runtime /Users/carolynvs/.porter/mixins/gcloud/gcloud-runtime
```

That will build the mixin for your current os and arch, along with a build suitable for the runtime (linux amd64), and then copy them into your PORTER_HOME directory.

Let me know if you have trouble with that and I'm super excited to know that you are making a mixin. 👍

**Comment by donmstewart** [comment]
Thanks for the super fast response. 

It worked first time and is installed. Now to check if it works properly :)
