### ISSUE TITLE
porter build using new mixin

### ISSUE THREAD

**Issue by donmstewart** [deislabs/porter#566]
Hi

It seems I am running into an issue with `porter build` and `porter install` with a custom mixin. I have a docker template similar to that in the aks sample. I run a `porter build` on my Mac and it creates the docker file, creates the `.cnab` directory with the mixins required by the `porter.yaml` file.  All looks good until I try the `porter install`.

The challenge seems to be as I am on the Mac the `.cnab/app/mixins/mixin/mixin-runtime` that is created using `porter build` is an OS X format binary not a Linux binary that is required in the container. I have tried doing a `make build-runtime` which correctly generates a linux format file in my `$HOME/.porter/mixins/mixin-runtime` but the `porter build` just then creates an OS X format binary at `.cnab/app/mixins/mixin/mixin-runtime` within the project and copies that into the container. Is there a way either to specify the target OS in order the correct `mixin-runtime` is built, placed into the   `.cnab/app/mixins/mixin` directory and hence copied into the container?

If I run `porter install --debug` the error on the output is: -

```fork/exec /cnab/app/mixins/mixin/mixin-runtime: exec format error```

**Comment by donmstewart** [comment]
Fixed by changing the following in the makefile to ensure the `$(RUNTIME_PLATFORM)` is in the installation of the `$(MIXIN)-runtime` (which I copied from the Helm makefile)

```
install:
	mkdir -p $(PORTER_HOME)/mixins/$(MIXIN)
	install $(BINDIR)/$(VERSION)/$(MIXIN)-$(CLIENT_PLATFORM)-$(CLIENT_ARCH)$(FILE_EXT) $(PORTER_HOME)/mixins/$(MIXIN)/$(MIXIN)$(FILE_EXT)
	install $(BINDIR)/$(VERSION)/$(MIXIN)-$(RUNTIME_PLATFORM)-$(RUNTIME_ARCH)$(FILE_EXT) $(PORTER_HOME)/mixins/$(MIXIN)/$(MIXIN)-runtime$(FILE_EXT)
```

**Comment by carolynvs** [comment]
I'm guessing there is some Makefile ordering missing somewhere. The chain should look something like this:

```
$ make build install

build: build-client build-runtime

build-client generates bin/mixins/MIXIN/MIXIN based on CLIENT_PLATFORM and CLIENT_ARCH. These are defaulted using go env
build-runtime generates bin/mixins/MIXIN/MIXIN-runtime based on RUNTIME_PLATFORM and RUNTIME_ARCH. These are defaulted by linux and amd64

install copies bin/mixins/MIXIN/MIXIN and bin/mixins/MIXIN/MIXIN-runtime into ~/.porter/mixins/MIXIN/
```

We use this same Makefile for every mixin so I'm wondering if something either was lost when altered to work for your mixin, or if we are missing something that doesn't work well outside of our workflow? 

If you have the Makefile to share I'd be happy to take a look. I'd like to get it right because we have a [template mixin repository](https://github.com/deislabs/porter-skeletor) that we are working on to help people get started and if there's a problem I'd like to fix it there too.

**Comment by donmstewart** [comment]
@carolynvs 

Yup all good now thanks. I'll retry the steps here to make sure it works as expected as I am doing something slightly different.

On another note we have a `kustomize` mixin working for the `install` action now and are working on `uninstall` and cleaning up the test cases which is good news (for us at least :) ).

**Comment by carolynvs** [comment]
Sweet! 💯

When you have it all finished, let me know and I will list it on the mixins page for others to find an use.

**Comment by jeremyrickard** [comment]
That's super exciting @donmstewart
