### ISSUE TITLE
porter hash doesn't take enough into account

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#572]
When we stamp the bundle.json with a hash of the porter.yaml, that isn't enough to tell that we should rebuild the bundle because it is out out date. 

* One example is when the porter binary itself has since been updated, usually with bug fixes. In that case, the hash should be considered stale and the bundle rebuilt automatically. We should incorporate the porter version and the list of mixins used in the bundle, along with their version in the stamp.
* Another case would be when a mixin that is used by the bundle is updated.
* Another is when files in the current directory (or below) are changed, excluding those from `.dockerignore`

p.s. I was pressured into making the stamp under `sh.porter` and have always regretted it. Now would be a good time to fix that before it's too late! 😀

**Comment by dev-drprasad** [comment]
@carolynvs I would like to pick this issue
