### ISSUE TITLE
Require credentials by default

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#577]
The spec(?)/cnab-go(?) changed at the last minute to make credentials optional. This is super confusing IMO and I think we should consider flipping this in Porter to having them be required by default, or do something to warn people.

Otherwise this is what happens:

1. Jeremy gives Carolyn a bundle that requires credentials.
2. Carolyn starts making the credentials by exporting env vars. She gets distracted and stops in the middle.
3. She runs the bundle and doesn't specify --cred, or she does specify but only half of the creds are defined.
4. THERE IS NO WARNING. The bundle just fails in odd places with unexpected errors because the bundle was written assuming credentials would be there, and they aren't.
5. Carolyn is confused because she thought she defined creds but nothing in Porter is warning her because "TADA! According to the spec, they are optional now".

Everyone intended for them to be required. Their mere presence looks like they are really needed, but sneakily they are optional.

I think they should be required by default, and if an author wants them optional, they should need to say that explicitly in the credential definition. We should also think about how to warn about missing optional credentials, so people at least realize that they _could_ have supplied something and didn't.

**Comment by carolynvs** [comment]
The following changes need to be made:

* Add a custom UnmarshalYAML function for [CredentialDefinition](https://github.com/deislabs/porter/blob/b24cdd412147c8156942f6d8accb489e71e48e6f/pkg/config/manifest.go#L107-L113) and set required to true.
* See [this comment](https://github.com/go-yaml/yaml/issues/165#issuecomment-255223956) for advice and sample code on how to accomplish this with the yaml encoder.
* Add a test to [manifest_test.go](https://github.com/deislabs/porter/blob/master/pkg/config/manifest_test.go)

**Comment by AGMETEOR** [comment]
Hello @carolynvs , I want to give this a shot

**Comment by carolynvs** [comment]
@AGMETEOR Go for it! 👍 If you run into trouble, feel free to open a draft pull request with your progress and ask questions there.

**Comment by vdice** [comment]
Closed by https://github.com/deislabs/porter/pull/657 👏 @AGMETEOR
