### ISSUE TITLE
Support deleting a mixin with the porter mixin delete command

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#613]
Support deleting a mixin with a new command

```console
$ porter mixin delete NAME
deleted NAME
```

The following changes need to be made:
* `cmd/porter/mixins.go` Add the delete command
* `cmd/porter/mixins.go` Add a function to Porter that handles the mixin command
* `pkg/mixins//mixin.go` Add the Delete function to the MixinProvider
* `pkg/mixins/provider/NEWFILE` Add delete.go and implement the delete functionality and add tests
* Link to the new command from the [doc nav](https://github.com/deislabs/porter/blob/master/docs/config.toml#L43)

Mixins are installed into PORTER_HOME/mixins/NAME. Delete a mixin by deleting the directory named after the mixin. If #610 has been implemented, you will also need to remove the entry from the mixin cache file as well.

**Comment by bradcypert** [comment]
👋 Howdy! I'm interested in trying to add this functionality! I can try to get something together within a day or so!

**Comment by carolynvs** [comment]
@bradcypert Sounds good!
