### ISSUE TITLE
Extend version command to help troubleshoot porter

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#614]
I want a command to help me troubleshoot when someone submits a bug report. Instead of having to asking questions about "what os are you running", "what mixins are installed?" etc, I'd rather tell them "run this one command and send me the output".

I think we can add a `--system` flag that when present prints additional information about what is installed in the porter home directory.

```console
$ porter version --system
porter v0.14.1-beta.2 (72dd5df)

System
--------
os: darwin
arch: amd64

Mixins
------
Name         Version          Author
aws          v0.1.2-beta.1    DeisLabs
az           v0.2.1-beta.1    DeisLabs
```

The following will need to be changed:
* `cmd/porter/version.go` - add system flag
* `pkg/porter/version.go` - 
  * Add VersionOpts struct to hold what we use currently plus the system bool and have version take this new opts struct instead.
  * Add method to collect additional information when system flag is present (os, arch)
  * Use [porter.ListMixins](https://github.com/deislabs/porter/blob/b24cdd412147c8156942f6d8accb489e71e48e6f/pkg/porter/mixins.go#L42) to get a list of the installed mixins, and use similar table printing as [porter.PrintMixins](https://github.com/deislabs/porter/blob/b24cdd412147c8156942f6d8accb489e71e48e6f/pkg/porter/mixins.go#L26-L30)
  * Make a new struct to contain all the collected information and handle printing it according to the requested output format (json, table, etc).
  * Add tests to version_tests.go

**Comment by phillipahereza** [comment]
@carolynvs can I give this a shot?

**Comment by carolynvs** [comment]
@phillipahereza  You bet!

**Comment by phillipahereza** [comment]
@carolynvs what output formats should I allow with the system flag because `port mixins list` allows `table` output while `porter version` doesn't. Should I ignore the table output for the system flag?

**Comment by carolynvs** [comment]
@phillipahereza Yes, each command in porter may support a different set of format values. So just go with what `porter` version already supports: json, plaintext. 👍

**Comment by phillipahereza** [comment]
@carolynvs how do I build my latest changes? Every time I run `make build-porter`, it builds a specific commit
