### ISSUE TITLE
Short circuit build for documentation changes

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#623]
When the change is not related to code, we shouldn't have to wait for the entire porter build to go. It should short circuit and complete early.

* Changes to md files at the root of the directory, or to docs should not trigger a full azure pipelines run.

**Comment by lewiscowper** [comment]
@carolynvs I'd love to work on this, but I'm not 100% clear on the requirements, do the docs need to run some part of some job on azure pipelines, or none at all?

**Comment by carolynvs** [comment]
@lewiscowper Just checking in to see if you need any further clarification or want to throw this issue back for others to pick up.

**Comment by lewiscowper** [comment]
apologies I got a bit snowed under and haven't had a chance to look into much yet, I was hoping there would be a nice regex or something in azure pipelines that'd work like `only: ![docs,*.md]` or something, but as far as I can see in azure docs I can't find anything like that. But you're welcome to throw it back for others to pick up. Apologies for taking it over.
