### ISSUE TITLE
Installation script messes up $PATH in ZSH

### ISSUE THREAD

**Issue by jonatasbaldin** [deislabs/porter#626]
## Describe the bug
Hi there 👋

When installing Porter using the [official docs](https://porter.sh/install/#latest-macos) on MacOS I got a bug when the last command is executed, `export PATH=\$PATH:~/.porter`.

In my ZSH, it messed up with my `$PATH` environment variable:
```
$ echo $PATH
PATH:/Users/jonatasbaldin/.porter
```

So all my binaries become unavailable in that session 🙈 

## To Reproduce
1. Open a ZSH session (mine is `v5.7.1`)
2. Install porter with MacOS command from [here](https://porter.sh/install/#latest-macos)
3. After the installation is finished, execute `export PATH=\$PATH:~/.porter`, the command documented in the installation script
4. Execute `echo $PATH`
5. Should return something like `$PATH:/path/to/porter`

## Expected behavior
To just append `/path/to/porter` into my `$PATH` var.

**A quick fix is to change the command to** `export PATH=$PATH:~/.porter`, **removing the trailing slash**. I tested in ZSH and Bash (v5) and it worked!

I can make a PR to fix it ✨

## Version
porter v0.15.0-beta.1 (d28329a)

**Comment by jeremyrickard** [comment]
Hey @jonatasbaldin thanks for trying out Porter and reporting this. I tried reproducing with a zsh session (5.2) and didn't encounter an error. I'll try upgrading and see if I can reproduce. In the meantime, feel free to submit a PR! We welcome all contributions!

**Comment by jeremyrickard** [comment]
@jonatasbaldin could you confirm if you copied the line that was echoed from running the script or if you copied that line out of the script?

**Comment by squillace** [comment]
yeah, I can't repro: here's the output from the last time I ran this install on mac/zsh (about three hours ago): 

```
az v0.2.1-beta.1 (78db159) by DeisLabs
installed aws mixin
aws v0.1.2-beta.1 (96cd976) by DeisLabs
installed gcloud mixin
gcloud v0.2.1-beta.1 (bd072bd) by DeisLabs
Installation complete.
Add porter to your path by running:
export PATH=$PATH:~/.porter
```

note the last bit: there's no extra slash.

**Comment by jonatasbaldin** [comment]
Oh, @jeremyrickard is right, I copied the line from the script, but it's not echoed in the screen after the installation 🤦‍♂ 

Thanks for the support peeps, will close this ✨
