### ISSUE TITLE
[enhancement] Let's add a `porter explain` or `porter inspect` command 

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#635]
**Background:**

Someone building a Porter bundle can `publish` it to an OCI registry and then other people can `install`  or `credential generate` from that tag. One thing that we don't really have a good story for is how do you discover the parameters and credentials that are required and how do you discover what outputs are produced  or what custom actions are available?  You could try and `install` the bundle over and over until you get it right or perhaps find documentation in a Github repo or README that someone shared with you out of band, but wouldn't it be better if we could do all of that from Porter?

**What this issue proposes:**

What if we add a new command to porter that is purpose built to help users learn about a bundle? This command could print out information about the bundle, such as parameter, output and credential definitions, as well as list the custom actions available, and we could support this from a tagged reference, just like `install` and `credentials generate`. 

I'm not 100% sold on which `subcommand` we want to surface (the two in my head right now are `explain` and `inspect`), but it might look something like this:

```
$ porter bundle explain --tag deislabs/tron:v1.0.2

name: Tron
description: "The classic game of light cycles and disc wars, deployed on your Nomad cluster" 
version: 1.2.2

==Parameters==
| Name             |   Type           |    Description   |       Default (Required)    | . Env or File  
<stuff>

==Credentials==
| Name |  Type | Description | Env or File
<stuff>

==Outputs== 
| Name             |   Type           |    Description   |       Default    | . Env or File  
<stuff>

==Actions==
| Name | Description | Stateless | Mutating | 
<stuff>
```

I'm not sure if we should print out all the JSON schema stuff for the params and outputs. Maybe we further have commands that drill into params and give you more info? 

```
$ porter bundle explain parameter --name name --tag <asdasdadadad>
```

We could also print out things in the custom section as we get to supporting other well known things. For example, we could determine that the bundle.json specifies dependencies and print those out as well. 

What do you think @carolynvs? This is partially inspired by `kubectl explain`:

```
kubectl explain pod
KIND:     Pod
VERSION:  v1

DESCRIPTION:
     Pod is a collection of containers that can run on a host. This resource is
     created by clients and scheduled onto hosts.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata

   spec	<Object>
     Specification of the desired behavior of the pod. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status

   status	<Object>
     Most recently observed status of the pod. This data may not be up to date.
     Populated by the system. Read-only. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
```

I think this could really improve the experience working with remote bundles.

**Comment by jeremyrickard** [comment]
This should maybe also print out the images that will be used?

**Comment by carolynvs** [comment]
There are a few personas here and we shouldn't try to mix them together into a single command that shows everything at the same time. Otherwise it's going to be overwhelming and a bit of a dump for the first persona.

1. Someone wants to use a bundle and wants to know what they need to provide the bundle to install it, what outputs it creates and what actions they can call on it.
2. Someone wants to audit or figure out what the bundle is going to really do. Either because they don't trust it or because they want to debug it.

Maybe there's a third but that's just addressing wanting to see creds/params vs. images referenced.

What do you think?

**Comment by jeremyrickard** [comment]
@carolynvs yeah, that's a valid point. I think #2 probably wants everything from #1, plus the addition of the images that will be used (maybe if we ever allow you to select the invocation image, that comes into play in that command as well).  The first cut of this should just be the first, another issue for the second.
