### ISSUE TITLE
Check for missing ARG BUNDLE_DIR declaration in dockerfile template

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#655]
When the dockerfile template doesn't have `ARG BUNDLE_DIR` in it, the docker build doesn't provide a useful error back to the user that hints what is wrong. Instead it just says this:

```
Starting Invocation Image Build =======>
Error: unable to build CNAB invocation image: failed to stream docker build output: cannot normalize nothing
```

Thankfully @clarenceb figured it out and fixed it in our azure workshop example, but it's an easy mistake to make and we should help provide a better error message when that happens.

Before a build, porter should look at the lines in the dockerfile template for `ARG BUILD_DIR` and if it's not present, return an explicit error

```
dockerfile.tmpl must declare the build argument BUILD_DIR. Add the following line to the file and re-run porter build:
ARG BUILD_DIR
```

This check should happen in:

https://github.com/deislabs/porter/blob/master/pkg/build/dockerfile-generater.go `getBaseDockerfile` which probably needs to be refactored into multiple functions now that we want to put more logic into it around validating the user supplied template.

**Comment by AGMETEOR** [comment]
@carolynvs I am going to try this one out...

**Comment by carolynvs** [comment]
Thanks!

**Comment by AGMETEOR** [comment]
Started working on this. Apologies for the delay.
