### ISSUE TITLE
Custom help template not used for published version of porter

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#656]
## Describe the bug
When I build porter locally, then run `porter help` I see the custom help template. But when I use a published release of porter, I don't.

## To Reproduce
1. Install porter from the https://porter.sh/install
2. Run `porter help`

## Expected Output

```
$ porter help
I am porter 👩🏽‍✈️, the friendly neighborhood CNAB authoring tool

Usage:
  porter [command]

Examples:
  porter create
  porter build
  porter install
  porter uninstall

Resources:
  bundles     Bundle commands
  credentials Credentials commands
  instances   Bundle Instance commands
  mixins      Mixin commands

Aliased Commands:
  archive     Archive a bundle
  build       Build a bundle
  create      Create a bundle
  install     Install a new instance of a bundle
  invoke      Invoke a custom action on a bundle instance
  list        list instances of installed bundles
  publish     Publish a bundle
  show        Show an instance of a bundle
  uninstall   Uninstall a bundle instance
  upgrade     Upgrade a bundle instance

Meta Commands:
  docs        Generate markdown docs
  schema      Print the JSON schema for the Porter manifest
  version     Print the application version
```

## Actual Output
```
$ porter help
I am porter 👩🏽‍✈️, the friendly neighborhood CNAB authoring tool

Usage:
  porter [command]

Examples:
  porter create
  porter build
  porter install
  porter uninstall

Available Commands:
  build       Build a bundle
  bundles     Bundle commands
  create      Create a bundle
  credentials Credentials commands
  docs        Generate markdown docs
  help        Help about any command
  install     Install a new instance of a bundle
  instances   Bundle Instance commands
  invoke      Invoke a custom action on a bundle instance
  list        list instances of installed bundles
  mixins      Mixin commands
  publish     Publish a bundle
  schema      Print the JSON schema for the Porter manifest
  show        Show an instance of a bundle
  uninstall   Uninstall a bundle instance
  upgrade     Upgrade a bundle instance
  version     Print the application version
```

## Version
Copy the output of `porter version` below

porter v0.16.1-beta.1 (f1f5217)

**Comment by dev-drprasad** [comment]
@carolynvs I would like to work on this issue. This will be my first contribution to porter. So, i may need help

**Comment by carolynvs** [comment]
@dev-drprasad Sure! 

I normally recommend that new contributors pick up one of the good first issue or help wanted from our [New Contributor Guide](https://porter.sh/contribute). Those have pointers on how to implement the fix or enhancement. 

But I would like help with this bug! ❤️  I have looked at it and I'm not sure what is causing them problem. So I am more than happy to help but just fair warning that I don't know the solution. 😅

**Comment by dev-drprasad** [comment]
No problem. I can figure it out.
I am not able to find development setup steps. Don't i have to configure anything after clone ?

**Comment by carolynvs** [comment]
@dev-drprasad Sorry I didn't see your comment sooner! The contributing guide has the initial setup

https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#initial-setup

If you ever run into something weird where the guide says one thing, but it needs extra steps to work, I'd really appreciate help keeping the guide up-to-date!
