### ISSUE TITLE
porter maybe can cache old bundle versions forever

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#678]
## Describe the bug
I have seen this locally when working on the integration tests (for dependencies with the mysql and wordpress bundles). It was also just reported in Slack as well.

## To Reproduce
I'm not totally sure but I'm guessing it looks something like this:

1. Publish a bundle with under a version, e.g. 1.0
2. Run `porter install --tag mybuns:v1.0`
3. Make changes to that bundle and republish to that same version again
4. Run `porter install --tag mybuns:v1.0` again

## Expected behavior
The user expects it to use the latest version of that bundle.

I'm not sure how porter knows to expire the cache for that tag? Maybe it's just a problem for local developers who are pushing and repushing the same tag, so when we publish, we should nuke the cache for that bundle and tag combo?

## Version
v0.16.0-beta.1

**Comment by vdice** [comment]
Ah, I've been running into this as well.  Indeed, currently, Porter simply caches using a hash of the bundle tag.  Therefore, if digest/contents change whilst still using the same tag, no new cache entry will be generated.

We probably need to add additional unique info (digest/etc.) when generated the cached bundle hash?  The only tricky bit is ensuring it is still easy to find a cached bundle purely on bundle tag (or, perhaps we can update this logic to incorporate the same unique info.)
