### ISSUE TITLE
`porter mixins list` feels slow on Windows

### ISSUE THREAD

**Issue by itowlson** [deislabs/porter#680]
## Describe the bug
When I run `porter mixins list` on Windows, it takes about 6 seconds (for the 8 default mixins I have installed).

## To Reproduce
0. Install Windows on a PC that is admittedly a few years old but is still decently grunty
1. Run `porter mixins list`
2. Start counting under your breath
3. Wait for output to appear
4. Stop counting and go "gosh that felt a bit slow"

## Expected behavior
Expected output to appear within a second or so.

## Porter Command and Output
```
D:\GitHub\vscode-mock-debug [master ≡]> C:\Users\itowlson\.porter\porter.exe mixins list
Name         Version          Author
aws          v0.1.2-beta.1    DeisLabs
az           v0.3.1-beta.1    DeisLabs
azure        v0.7.1-beta.1    DeisLabs
exec         v0.17.0-beta.1   DeisLabs
gcloud       v0.2.1-beta.1    DeisLabs
helm         v0.8.0-beta.1    DeisLabs
kubernetes   v0.17.0-beta.1   DeisLabs
terraform    v0.4.1-beta.1    DeisLabs
```

## Version
Copy the output of `porter version` below

`porter v0.17.0-beta.1 (1a5ae4b)`

**Comment by carolynvs** [comment]
On my windows machine I am able to reproduce but I'm not sure if it's the same thing. The very first time after a reboot, that command is slow. Every time afterwards though it returns immediately (porter does not cache the result in any way).

When you run the command twice in a row, is the timing about the same?

**Comment by itowlson** [comment]
The timing is different though still slow.  I just ran it after not using Porter for a while, and it was a count of 11.  Then I ran it twice again and both times it was a count of 7.  I don't want to reboot right now to see if first after reboot is different again *grin* - but can do so sometime if you need.

**Comment by carolynvs** [comment]
This is Windows 10 right?

**Comment by itowlson** [comment]
Yes, Windows 10 Version 1903.

**Comment by squillace** [comment]
ditto this experience. a full 20 seconds just now after a reinstall; but in between, the antivirus notification said "hold on, bucko, something needs scanning". Ivan, I'd test that first time with an eye on the AV process..... once scanned, it still takes 6 seconds, which is totes weird.

**Comment by carolynvs** [comment]
I have changed this code to execute in parallel. Have the performance changed at all? I haven't tested on a machine with the MSFT antivirus so I will need your help to confirm.

**Comment by itowlson** [comment]
For me it's still a bit slow first time (count of 6 on my laptop) but then quick.

**Comment by iennae** [comment]
Thanks for getting back about your current experience. This sounds like the code refactor to execute in parallel has improved the subsequent runs. At this time, we aren't going to be able to fix the cold start latency. Please do reopen if there is more that we need to address in this issue. Thanks!
