### ISSUE TITLE
Image Relocation: Store relocation map alongside published bundle

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#687]
Once Porter has image relocation (established way to relocate bundle images whilst preserving digests; see https://github.com/deislabs/porter/issues/543), it would be worthwhile to see if we can add functionality to store the image relocation map in a registry alongside a bundle on publishing.  Classically, this map has been a separate asset, expected to be provided at runtime.

**Comment by jeremyrickard** [comment]
I don't think we need to handle this, per @radu-matei and Silvin it will just be regenerated on a pull.
