### ISSUE TITLE
Running porter publish against a GitHub Registry fails

### ISSUE THREAD

**Issue by MikeLarah** [deislabs/porter#695]
Running `porter publish` against a GitHub Registry fails with following error:

```
porter publish
Pushing CNAB invocation image...
The push refers to repository [***/***/***/***]
42d8f65d44b0: Preparing
9c5c2fd08f70: Preparing
071e32105484: Preparing
0efb497bf891: Preparing
55e6b89812f3: Preparing
42d8f65d44b0: Retrying in 5 seconds
071e32105484: Retrying in 5 seconds
42d8f65d44b0: Retrying in 4 seconds
071e32105484: Retrying in 4 seconds
071e32105484: Retrying in 3 seconds
42d8f65d44b0: Retrying in 3 seconds
071e32105484: Retrying in 2 seconds
42d8f65d44b0: Retrying in 2 seconds
42d8f65d44b0: Retrying in 1 second
071e32105484: Retrying in 1 second
42d8f65d44b0: Pushed
9c5c2fd08f70: Pushed
071e32105484: Pushed
55e6b89812f3: Pushed
0efb497bf891: Pushed
0.1.0: digest: sha256:f695161eefa9fcd7316e4dcbb67c3131b49968aa2774065100db4313035b5c57 size: 1374
Error: unable to push CNAB invocation image: unable to inspect docker image: Error response from daemon: manifest unknown: Docker image reference ***:sha256:f695161eefa9fcd7316e4dcbb67c3131b49968aa2774065100db4313035b5c57 not found under repo "***/***"
```

**Comment by jeremyrickard** [comment]
Thanks for reporting this! We haven't tested against Github yet, only Dockerhub and I think ACR? I'll dig into this and let you know!

**Comment by HowardvanRooijen** [comment]
We can confirm it works against ACR as that's what we reverted to after the GitHub Package Registry failed.

**Comment by MikeLarah** [comment]
I raised this with GitHub support too, and this was their response:

**Comment by MikeLarah** [comment]
I raised this with GitHub support too, and this was their response:

> Unfortunately, at present, we only support the documented build tools and clients, in this case docker:
https://help.github.com/en/articles/about-github-package-registry
I will however pass this over to our team as a feature request. This is something we are exploring going forward, as each of these package formats support a wide range of build tools and clients beyond the 'default' option.
Keep an eye on our documentation and https://github.blog/changelog for updates.

**Comment by squillace** [comment]
I recommend closing this, as it's not a Porter issue, but rather an OCI registry issue.

**Comment by carolynvs** [comment]
We need up update our list of compatible registries and then this can be closed out.

https://porter.sh/compatible-registries/
