### ISSUE TITLE
Porter archive on bundle that has yet to be published

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#697]
## Describe the bug
`porter archive mybuns.tgz` will fail if the invocation image hasn't been published yet

## To Reproduce
1. Run `porter archive mybuns.tgz` for a bundle using an invocation image that hasn't yet been published
2. See error similar to: `Error: Error preparing artifacts: MANIFEST_UNKNOWN: manifest unknown; map[Tag:0.1.0]`

## Expected behavior
`porter archive mybuns.tgz` should finish successfully

Perhaps we ensure `porter publish` is called first in this scenario?  This would push the invocation image and bundle.json.  Or, perhaps we only push the invocation image.

## Porter Command and Output
```
 $ porter archive basic-tf.tgz
Error: Error preparing artifacts: MANIFEST_UNKNOWN: manifest unknown; map[Tag:0.1.0]
```

## Version
Copy the output of `porter version` below

`porter v0.17.0-beta.1-20-g6b882e0 (6b882e0)`

**Comment by carolynvs** [comment]
I believe we just need to push the invocation images because the archive needs their registry digests.

**Comment by vdice** [comment]
Also proposed by @squillace and others: we can instead just document this behavior for now.
