### ISSUE TITLE
Give the author control over where mixin dockerfile lines are inserted

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#707]
Allow the author to optimize their dockerfile, or take advantage of actions performed by the mixins, by allowing them to control where the dockerfile lines generated by the mixins are inserted into the custom dockerfile template.

When the user adds a line `# PORTER_MIXINS` to their dockerfile, porter will replace that line with the generated dockerfile lines from the mixins.

If that line is not present, then the mixin dockerfile lines are appended to the end of the dockerfile template.

The default [Dockerfile](https://github.com/deislabs/porter/blob/master/pkg/templates/templates/build/Dockerfile) should be updated as well to place `# PORTER_MIXINS` on the line before the `COPY`s.

**Comment by carolynvs** [comment]
This is a straightforward change, which is why I flagged it with `help wanted`. Any of our intrepid contributors can tackle this, or one of the maintainers if we need to complete it before a major demo.

**Comment by ThorstenHans** [comment]
Nice one. I'd like to start working on this issue. What I've spotted so far (just looked into the repo while having my first ☕️ this morning), is that `./pkg/build/dockerfile-generator.go` looks like a good place to start 😄  Or am I totally wrong?

**Comment by carolynvs** [comment]
@ThorstenHans That's the spot! It would be great if you'd like to take it on because it is making @squillace twitch, and he's pinging me on slack constantly to complain about his slow builds. 😂 

Since your are a regular contributor now I've added you to our org so that we can officially assign issues. 🌟 I have no idea if you could have assigned it to yourself? 🤔 If you have that power, feel free to do so for other issues in the future.

We have a [Contributor Ladder](https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#contribution-ladder) that lays out how it all works. Let us know if it's clear as mud, as it's kind of a new thing and probably needs improvement.

**Comment by ThorstenHans** [comment]
Hey @carolynvs thanks for adding me.

I've already drafted a PR, I struggled a bit with the unit-test (still new in the golang world) but did my best. 

I've described the struggle in the PR #712 

I'd love to get some feedback on that one to improve my golang quickly💃

**Comment by ThorstenHans** [comment]
BTW, I was not sure where documentation for the change would fit best. What do you think?

Or should I add the `# PORTER_MIXINS` (`INJECT_PORTER_MIXINS_TOKEN`) to the default `Dockerfile.tmpl` and add some documentation there (to have something in first place)

**Comment by squillace** [comment]
@ThorstenHans does https://github.com/deislabs/porter/pull/712#issuecomment-540610831 have anything to help there?

**Comment by ThorstenHans** [comment]
Hey @squillace,

Yep that helps. Will look into it tomorrow evening CEST. Was sick, still need some time to recover 😕
