### ISSUE TITLE
Docs don't do syntax highlighting

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#716]
## Describe the bug
On our doc pages, even though I'm doing code fences and declare the language, the proper css to highlight the syntax isn't being applied to make the code look pretty.

## To Reproduce
https://porter.sh/docs/

## Expected behavior
Pretty code on our doc pages, such as yaml or go snippets being highlighted. Whatever we do shouldn't make the console/bash look awful.

**Comment by SuddenGunter** [comment]
@carolynvs I've got a fix for this in PR above
