### ISSUE TITLE
Introduce a `porter copy` command

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#733]
We should add a `porter relocate` command that allows someone to copy a bundle from one registry to another registry, bringing along all associated images as well. We have most of the smarts for this with cnab-to-oci and Pivotal's image relocation logic, so this would mostly just be adding some good user experience around them. 

The flow might be something like this:

Jane, a DevOps super-hero at PonyCorp, discovers a really cool bundle in the `deislabs` registry. It does everything her organization needs to do. However, Bob, the friendly information security team member, insists that everything live in a private registry that they have full control over. Jane says, "don't worry Bob, Porter has us covered". Jane then runs the `porter relocate` command and moves the bundle, along with all referenced images, into PonyCorp's registry. 

If you have ideas about the UX for this, drop them below as a comment!

**Comment by carolynvs** [comment]
I suggest the following command:

```
porter copy --source-bundle deislabs/ponies:v1 --destination-registry registry.ponycorp.com
```

* --source-bundle|s - The fully qualified source bundle including version/tag.
* --destination-registry|d - the registry to copy the bundle to. Could be just the registry name or could be registry plus a repo prefix. All images and the bundle will be prefixed with this.

I'm going to dream big and suggest `copy` instead of `relocate` because it makes it clear in the name that the original bundle isn't modified. Basically the verb is more familiar and requires less explaining. It's the verb we use as soon as we explain "what is relocate" anyway so why not use it?

**Comment by squillace** [comment]
and it IS a true copy -- the bundle isn't mutated. Are we making any statements about the identity of the bundle image layers here?

**Comment by jeremyrickard** [comment]
Yeah, I like copy, only mentioned “relocate” because someone mentioned it as a fine command in another issue. I’m on team copy.

**Comment by squillace** [comment]
I'd love to be extra clear here that porter does not attempt to ensure the digests are the same for images. They might be, but they might not be. It's a copy, not a byte-wise guarantee. Does this sound good for now?

**Comment by dev-drprasad** [comment]
I suggest `copy` command with flexibility. Just like linux `cp` command. People can copy within same registry or to diferent registry with bundle name optional

### Example:

#### same registry different bundle name.

```
porter copy --source ponies:v1 --destination ponies-dup:v1
```

#### different destination without bundle name. Bundle copied with source name

```
porter copy --source deislabs/ponies:v1 --destination registry.ponycorp.com
```

#### different destination with bundle name. Bundle copied with diff name

```
porter copy --source deislabs/ponies:v1 --destination registry.ponycorp.com/my-ponies:v1
```

**Comment by carolynvs** [comment]
For the `--source` we aren't working from a porter bundle on disk with a porter.yaml, so it will need to be fully qualified. However I do like having a destination that is more flexible. 👍

**Comment by jeremyrickard** [comment]
I’ve got this mostly implemented, I’ll make the destination more flexible.

**Comment by carolynvs** [comment]
I liked @dev-drprasad 's smart destination unless that is a big pain. 😀
