### ISSUE TITLE
Porter explain doesn't take a driver flag

### ISSUE THREAD

**Issue by squillace** [deislabs/porter#757]
ralph@Azure:~$ porter explain --tag squillace/rudr-install-cnab:latest -d azure
Error: unknown shorthand flag: 'd' in -d

So you can't use explain for a remote bundle prior to using it. likely not what we intended, yes? Blocks explaining from cloud shell or any other driver environment.

**Comment by jeremyrickard** [comment]
You shouldn’t need a driver.? Did it fail without the driver? Explain doesn’t “run” anything.

**Comment by squillace** [comment]
I am stupid. Closing. :-)
