### ISSUE TITLE
porter explain can't explain a bundle that was installed using --tag

### ISSUE THREAD

**Issue by squillace** [deislabs/porter#758]
I guess it's only for the dev scenario?

ralph@Azure:~$ porter instances list
NAME           CREATED         MODIFIED         LAST ACTION   LAST STATUS
rudr-install   3 minutes ago   46 seconds ago   install       success
test19         2019-10-16      2019-10-16       install       success
ralph@Azure:~$ porter explain rudr
Name:
Description:
Version:

No credentials defined

No parameters defined

No outputs defined

No custom actions defined

**Comment by jeremyrickard** [comment]
Explain doesn’t work off instances. It works off a bundle file, a tag or a JSON file. We could enhance it, but currently it doesn’t. I don’t follow your “dev scenario”.
