### ISSUE TITLE
Porter should have a way to report schema both for itself and its mixins

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#76]
The parameters and output format for the Mixins can vary so we should provide a way for users to interrogate the mixins to get the schema.

**Comment by carolynvs** [comment]
Spoke with @itowlson and it sounds like we need a command that returns json schema. So we will need to iterate on this issue a bit with him and then we can make that happen!

**Comment by carolynvs** [comment]
See https://github.com/deislabs/porter-helm/pull/7 for progress on this and https://github.com/deislabs/porter/issues/116#issuecomment-454570979 as a related feature. I'll use this issue to track the feature as a whole.
