### ISSUE TITLE
Porter Copy and then porter install from new location fails.

### ISSUE THREAD

**Issue by squillace** [deislabs/porter#765]
## Describe the bug

Using bundle squillace/rudr-install-cnab:v0.1.0 (https://github.com/squillace/testing), after copying the bundle the install runs, but it takes forever and then fails out with some small issue in the helm chart.

## To Reproduce
1. See output for the commands:
> a. porter copy
> b. porter install

## Expected behavior
The same installation that occurred when porter install was called from the original image.

## Porter Command and Output
 🔋 100%  porter copy --source squillace/rudr-install-cnab:v0.1.0 --destination squillace.azurecr.io/rudr-cnab:v0.1.0
Beginning bundle copy to squillace.azurecr.io/rudr-cnab:v0.1.0. This may take some time.
Starting to copy image squillace/rudr-install:v0.1.0...
Completed image squillace/rudr-install:v0.1.0 copy
Starting to copy image oamdev/rudr@sha256:599b1b2a94a2ec3eb0ec1773e2c83dabbdcd4595f82f6d1d5ce9f97655c70733...
Completed image oamdev/rudr@sha256:599b1b2a94a2ec3eb0ec1773e2c83dabbdcd4595f82f6d1d5ce9f97655c70733 copy
Starting to copy image oamdev/rudr@sha256:59df102b6c2f63b2e712f407836c0019d7310daa681556963662eec1663f1ab5...
Completed image oamdev/rudr@sha256:59df102b6c2f63b2e712f407836c0019d7310daa681556963662eec1663f1ab5 copy
Bundle tag squillace.azurecr.io/rudr-cnab:v0.1.0 pushed successfully, with digest "sha256:2b07592d82f3e5829c852fb0b7a52b25f2ad428aad074d095d9e9648625f01b2"
 🔋 100%  porter install --tag squillace.azurecr.io/rudr-cnab:v0.1.0 -c rudr-install  ✔  10176  00:33:30
installing rudr-install...
Unable to find image 'squillace.azurecr.io/rudr-cnab@sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1' locally
sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1: Pulling from rudr-cnab
Digest: sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1
Status: Downloaded newer image for squillace.azurecr.io/rudr-cnab@sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1
executing install action from rudr-install (bundle instance: rudr-install) defined in /cnab/app/porter.yaml
Deploy rudr using Helm 3. This performs an upgrade --install, ensuring a complete installation with this chart.
Release "rudr" does not exist. Installing it now.
Error: timed out waiting for the condition
err: error running command helm3 upgrade --install rudr rudr --wait --set image.digest="sha256:59df102b6c2f63b2e712f407836c0019d7310daa681556963662eec1663f1ab5" --set image.repository="squillace.azurecr.io/rudr-cnab": exit status 1
Error: error running command helm3 upgrade --install rudr rudr --wait --set image.digest="sha256:59df102b6c2f63b2e712f407836c0019d7310daa681556963662eec1663f1ab5" --set image.repository="squillace.azurecr.io/rudr-cnab": exit status 1
Error: mixin execution failed: exit status 1
Error: failed to install the bundle: container exit code: 1, message: <nil>
 🔋 100%  time                                                                      1 ↵  10177  00:39:32
shell  11.69s user 3.08s system 0% cpu 16:07:52.48 total
children  79.33s user 43.54s system 0% cpu 16:07:52.48 total
```

## Version
Copy the output of `porter version` below
porter v0.20.0-beta.1 (bd40408)

**Comment by squillace** [comment]
![porter-copy-failure](https://user-images.githubusercontent.com/1422718/67370467-8d09ab80-f52f-11e9-98bd-b2bfb75bd45b.gif)

**Comment by squillace** [comment]
Naturally, I'm not clear but that there's a small issue with the chart, but also that perhaps copy wasn't expecting this precise usage pattern?

**Comment by jeremyrickard** [comment]
I’ve copied and installed before. The error you show doesn’t really indicate that it was related to copy at all. Seems like we are missing error context on the error message. Maybe the Nixon is missing errors.Wrap.

You were running the invocation image, so the copy seems to have at least moved that over.

**Comment by carolynvs** [comment]
Agreed, this seems to be a problem that isn’t related to the copy. 

p.s. I love that autocorrect changes mixin to Nixon. 😂

**Comment by squillace** [comment]
Trying again now, finally

**Comment by squillace** [comment]
No, there's something wrong here. I can copy to and from docker hub, but the cluster can't pull:

```
╭─ralph at surfacebook in ~/work/go/src/github.com/squillace/testing on master✘✘✘ using
╰─± porter copy --source squillace/rudr-install-cnab:v0.1.0 --destination squillace/rudr:v0.1.0
Beginning bundle copy to squillace/rudr:v0.1.0. This may take some time.
Starting to copy image squillace/rudr-install:v0.1.0...
Completed image squillace/rudr-install:v0.1.0 copy
Starting to copy image oamdev/rudr@sha256:599b1b2a94a2ec3eb0ec1773e2c83dabbdcd4595f82f6d1d5ce9f97655c70733...
Completed image oamdev/rudr@sha256:599b1b2a94a2ec3eb0ec1773e2c83dabbdcd4595f82f6d1d5ce9f97655c70733 copy
Starting to copy image oamdev/rudr@sha256:59df102b6c2f63b2e712f407836c0019d7310daa681556963662eec1663f1ab5...
Completed image oamdev/rudr@sha256:59df102b6c2f63b2e712f407836c0019d7310daa681556963662eec1663f1ab5 copy
Bundle tag docker.io/squillace/rudr:v0.1.0 pushed successfully, with digest "sha256:8b531cc1045cd9bcb7a12b20b4551ad51ce33ab7589551a4e20ff10e6f17113b"
╭─ralph at surfacebook in ~/work/go/src/github.com/squillace/testing on master✘✘✘ using
╰─± porter install --tag squillace/rudr:v0.1.0 -c rudr-install
installing rudr-install...
Unable to find image 'squillace/rudr@sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1' locally
sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1: Pulling from squillace/rudr
Digest: sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1
Status: Downloaded newer image for squillace/rudr@sha256:76adab50d2c0707e75d12062ae7a7a126deacd2b41addd98a0d99f2d6b20eae1
executing install action from rudr-install (bundle instance: rudr-install) defined in /cnab/app/porter.yaml
Deploy rudr using Helm 3. This performs an upgrade --install, ensuring a complete installation with this chart.
Release "rudr" does not exist. Installing it now.
^C
```

**Comment by squillace** [comment]
darnit, wait. something ELSE is wrong and I must ensure it first.

**Comment by squillace** [comment]
Something else WAS wrong. I am closing because you all do amazing work. It's the USERS, darnit, the USERS who have problems, amirite?
