### ISSUE TITLE
Keep claim for uninstalled bundles

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#770]
Instead of removing the claim when a bundle is uninstalled, and losing all record that it was installed, and when it was uninstalled. Let's investigate if we can record the uninstall in the claim instead.

Some of this is enshrined in cnab-go, perhaps because behavior from duffle was copied into that library and the spec is not clear on the uninstall behavior that must be implemented.

This is part of our general preference to preserve an audit trail and not just the last performed action.

**Comment by squillace** [comment]
audit trails good. only last performed action bad. This is the Way.

**Comment by carolynvs** [comment]
Closed by #1065
