### ISSUE TITLE
List plugins command

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#774]
🚨 This relies on plugins reporting the types and implementations they contain (#775). Right now they just report version and author.

Add a command similar to `porter mixins list` that lists installed plugins.

```
$ porter plugins list
Name        Type                 Implementation    Version                 Author
azure       instance-storage     blob              v0.1.2-beta.1           DeisLabs
aws         instance-storage     s3                v0.1.0                  Amazon
```

**Comment by dev-drprasad** [comment]
Hi @carolynvs , if this is not done yet, i would like to pickup.

**Comment by squillace** [comment]
I'd also suggest that we include repository location if possible.

**Comment by carolynvs** [comment]
Hey @dev-drprasad I just realized that I missed the notification on this and never replied back! 😬 If you would still like to work on this please feel free! In the future, you should be able to comment and assign issues to yourself, you are a member of the org now, so you don't need to ask and wait for us anymore. ❤️

**Comment by dev-drprasad** [comment]
Hi @carolynvs ,

I see you referenced issue #775 with this and you mentioned `plugin version --output json` contains `implementations` which is an array. 
Does it mean each plugin has multiple implementations ?
If so, then what should `porter plugin list` return ? list of plugins or list of implementations ?
