### ISSUE TITLE
porter creds generate does not function in PowerShell ISE

### ISSUE THREAD

**Issue by chasat-ms** [deislabs/porter#780]
## Describe the bug
porter creds generate does not function in PowerShell ISE

## To Reproduce
1. Run porter creds generate --tag squillace/cnab-tina:latest on a Windows 10 machine in a PowerShell ISE window launched as Admin Privs
2. See following result... 

PS C:\Users\chasat\.kube> porter creds generate --tag squillace/cnab-tina:latest
Generating new credential cnab-tina from bundle cnab-tina
==> 7 credentials required for bundle cnab-tina
[1;92m? [0m[1;99mHow would you like to set credential "azure-subscription-id"[0m  [36m[Use arrows to move, space to select, type to filter][0m
[1;99m  specific value[0m
[1;36m> environment variable[0m
[1;99m  file path[0m
[1;99m  shell command[0m

## Expected behavior
PS C:\> porter creds generate --tag squillace/cnab-tina:latest
Generating new credential cnab-tina from bundle cnab-tina
==> 7 credentials required for bundle cnab-tina
? How would you like to set credential "azure-subscription-id" specific value
? Enter the value that will be used to set credential "azure-subscription-id" 6b736da6-3246-44dd-a0b8-b5e95484633d
? How would you like to set credential "controller_password" specific value
? Enter the value that will be used to set credential "controller_password" password
? How would you like to set credential "controller_username" specific value
? Enter the value that will be used to set credential "controller_username" chasat
? How would you like to set credential "docker_password" specific value
? Enter the value that will be used to set credential "docker_password" password
? How would you like to set credential "docker_username" specific value
? Enter the value that will be used to set credential "docker_username" chasat
? How would you like to set credential "kube_config" specific value
? Enter the value that will be used to set credential "kube_config" C:\Users\chasat\.kube\config
? How would you like to set credential "mssql_sa_password" specific value
? Enter the value that will be used to set credential "mssql_sa_password" password
Saving credential to C:\Users\chasat\.porter\credentials\cnab-tina.yaml

## Porter Command and Output
```
$ porter creds generate --tag
lots of output
```

## Version
Copy the output of `porter version` below

porter v0.20.2-beta.1 (3df87f1)

**Comment by carolynvs** [comment]
Hi @chasat-ms, you should use the standard PowerShell terminal with Porter.

PowerShell ISE has limited support for interactive console applications and doesn't support colors, both of which porter uses in that command. That is a known limitation with PowerShell ISE and isn't something that we can fix on porter's end.

If you run into trouble with the standard PowerShell terminal please let us know as we do expect all the Porter commands to work just fine there so anything found is considered a bug.
