### ISSUE TITLE
Schema does not include images section

### ISSUE THREAD

**Issue by itowlson** [deislabs/porter#784]
## Describe the bug
The `porter schema` output does not include the `images` top-level attribute.

## To Reproduce
1. Run `porter schema >pschema.json`
2. Search `pschema.json` for the word `images`.

(or, load up a `porter.yaml` with an `images` map in `porter-vscode` and watch the squigglies flock to it)

## Expected behavior
No squigglies in VS Code.

## Porter Command and Output
```
$ porter schema
("lots of output" the template says and it's not kidding)
```

## Version
`porter v0.20.2-beta.1 (3df87f1)`

**Comment by jeremyrickard** [comment]
I'll take a look at this one
