### ISSUE TITLE
Installing azure-mysql-wordpress example, Helm error

### ISSUE THREAD

**Issue by benc-uk** [deislabs/porter#786]
## Describe the bug
Installing the example `azure-mysql-wordpress` fails with a Helm error. The install fails with "couldn't get kubernetes client: couldn't build kubernetes config"
The ARM resource(s) are created ok

## To Reproduce
1. Run steps in `examples/azure-mysql-wordpress/README.md`
2. Set a good password and server name in params.ini
3. Install the bundle

## Expected behavior
The bundle is installed

## Porter Command and Output
```
$  porter install --cred porter-azure-wordpress --param-file ./params.ini
installing porter-azure-wordpress...
executing install action from porter-azure-wordpress (bundle instance: porter-azure-wordpress) defined in /cnab/app/porter.yaml
Create Azure MySQL
Starting deployment operations...
Finished deployment operations...
Helm Install Wordpress
Error: couldn't get kubernetes client: couldn't build kubernetes config: Error loading config file "*******": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
Error: mixin execution failed: exit status 1
Error: 1 error occurred:
        * failed to install the bundle: container exit code: 1, message: <nil>
```

## Version
`porter v0.20.2-beta.1 (3df87f1)`

**Comment by benc-uk** [comment]
Note. I checked the creds and the `kubeconfig` parameter is pointing to my valid kube config file.
I can use Helm normally outside of Porter

**Comment by benc-uk** [comment]
I'm a complete idiot
My `kubeconfig` in my credentials set was pointing to my kube config file, but was of type "value" not "path"

**Comment by carolynvs** [comment]
I'm glad you figured it out quickly. 😀 

We have some issues in the backlog that should help make this less likely from happening in the future:
* Let bundles provide suggestions on what the credentials should look like (#326)
* Provide a way to create credentials without terminal interaction (#689)
