### ISSUE TITLE
Re-enable defaulting dependency parameters from the manifest

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#800]
We had to turn off defaulting dependency parameters from the manifest temporarily in #799. Once we have a solution for consistently having access to the manifest for both file based and tag based bundle execution, let's turn it back on.

**Comment by squillace** [comment]
What does it mean to "default dependency parameters" here? If you had the dependent manifest, you'd know what params are possible, but are we saying that we do not know what the "defaults" are for those params? or that we have access to them at all? In the sense of being able to inject them from the subordinate bundle invocation?
