### ISSUE TITLE
Proposal: Mixin Discoverability

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#808]
As a Porter author/user, I'd like to have a way to easily discover a full list (and/or search this list) of mixins available for use and/or for contributing to.  Although the bulk of Porter's mixins exist in this same org and are listed for perusal on the [website](https://porter.sh/mixins/), there already are a handful developed in other organizations, with the intention that they continue to be maintained there.

Naturally, we can add to the list linked to above, but I'd like to propose we add the ability to quickly search and/or get a list of all available mixins currently fetchable.  The two main ways to fetch mixins so far: via a [feed url](https://porter.sh/cli/porter_mixins_feed_generate/) or from the GH repo's [releases](https://porter.sh/mixin-dev-guide/distribution/#publish) page.

Perhaps as a first implementation, we can maintain a structured list (JSON?) in this repo with all known mixins, their retrieval urls/mechanisms and their corresponding GH repos.  This list would then be parsed by the cli for, say, a `porter mixins search` command.  As more mixins become available, their metadata as described above can be added in the form of a PR to said list.  

Thoughts/ideas?

**Comment by squillace** [comment]
If you don't think that's too difficult at the moment, it's a good thing to do. As the tool becomes more useful, more people will submit prs to add mixins to the file...… it's a thing.
