### ISSUE TITLE
Install mixins based on porter.yaml during build time

### ISSUE THREAD

**Issue by ffoysal** [deislabs/porter#813]
It would be great if `porter build` can install all the necessary `mixins` based on the list in `porter.yaml` file during build time. If those mixins are already installed `porter build` can just skip them.

Currently we have to install mixins separately though there is a list defined in `porter.yaml`.
as far as tool's installation is concerned customer need to  install only `porter`

**Comment by carolynvs** [comment]
That's a really great idea!

**Comment by carolynvs** [comment]
This has been expanded upon and is tracked in the epic #975
