### ISSUE TITLE
Create the run script if it doesn't exist on build

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#84]
The run script is created at `porter create` but really it's a boring file that we don't encourage people to modify. Let's make it so that if its not present during `porter build`, we recreate it for them. That way you can just check in the run script if you modified it.

**Comment by youreddy** [comment]
Hey @carolynvs, this looks like an interesting issue to tackle but I'm new to porter and might be missing some context. I'm unsure about how a bundle author would get into this scenario and what would be the expected outcome after running `porter build`?

**Comment by carolynvs** [comment]
Great! Here is what I did to get myself into this situation. 😊 

1. I didn't actually run `porter init`. I copied an existing porter.yaml from an example.
2. I then immediately ran `porter build` and it failed because the cnab directory and run script was missing.

Another way to have this problem is to do this

1. Run `porter init`, porter creates the cnab/ directory and run script (cnab/app/run).
2. Forget, or not understand, to check it in. Only check in the porter.yaml
3. Now go to another computer, or do a `git clean`, etc. You don't have a cnab directory and run script anymore.
4. Try to run `porter build` and you get an error again.

Both situations are pretty easy for porter to fix because the cnab directory and run script are easy for porter to recreate if missing during the build command.

What I hope to see is when the user runs `porter build`, the function "prepareDockerFilesystem" in https://github.com/deislabs/porter/blob/master/pkg/porter/build.go should check if run script exists at cnab/app/run. If not, it should execute the Create function again in https://github.com/deislabs/porter/blob/master/pkg/porter/create.go. 

If you need to reorganize the functions a bit, that's OK.

**Comment by carolynvs** [comment]
This has now been implemented
