### ISSUE TITLE
Porter doesn't wait docker container to stop

### ISSUE THREAD

**Issue by fenngwd** [deislabs/porter#842]
In old Docker API version, `exec` in cnab-go is not waiting container to finish execution.

cnab-go has fixed this bug. [https://github.com/cnabio/cnab-go/pull/169](url)

Please upgrading cnab-go to fix this problem.

**Comment by fenngwd** [comment]
Closing for waiting cnab-go to release.

**Comment by carolynvs** [comment]
We haven't seen any indication of this actually occurring. @fenngwd Do you have an example bundle that reproduces this bug so that we can add it to our regression test suite?

**Comment by fenngwd** [comment]
This bug will only occur in lower Docker version.(Like 1.12.6 which I'm using.). It's not about bundle, it's about Docker version.

**Comment by carolynvs** [comment]
Thanks for clarifying. I've [fixed a bug in cnab-go](https://github.com/cnabio/cnab-go/pull/171), and upgraded to the latest version of that library.
