### ISSUE TITLE
Refactor: Update applicable bundles to use the arm mixin

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#861]
There are several bundles that use the deprecated `azure` mixin.  While it's still out there and available to use, we'd like to establish the pattern of using its replacement, the `arm` mixin.

Therefore, the work in this PR is to update the bundles per the `arm` mixin and confirm they work as intended after the refactor.

**Comment by carolynvs** [comment]
Once we have completed this PR, we can remove the azure mixin from our mixin feed.

**Comment by squillace** [comment]
Hey @vdice, are they all in the examples repo?

**Comment by vdice** [comment]
@squillace some are in the `examples` dir and some in the `workshop` dir... just about wrapped up with the latter bundles...
