### ISSUE TITLE
Rethinking display of sensitive outputs in table display

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#863]
Now that outputs aren't stored in porter home anymore, displaying the path _inside the bundle runtime_ to the output doesn't seem helpful for sensitive outputs.

Here is what someone sees when they list outputs in table format:

```
-----------------------------------------------
  Name                 Type    Value (Path if sensitive)
-----------------------------------------------
  IP_ADDRESS           string  40.88.49.175
  STORAGE_ACCOUNT_KEY  string  /cnab/app/outputs/STORAGE_ACCOUNT_KEY
```

Back when the path was a local path to porter home, e.g. ~/.porter/outputs/BUNDLE/STORAGE_ACCOUNT_KEY, it made more sense. They could choose to go look and see if they had permission to view that file. But now that we display a path that is inaccessible, /cnab/app/... isn't available after a bundle has been run, I'd prefer that we think about what else to show.

## Options

A. Just show the value, regardless of sensitive or not (just like you would see if it's json/yaml). Why are tables special? **WINNER**

B. Show *** and only show the full value when they request the named output with `porter instance output show NAME`. 
What are we trying to avoid here? Someone looking over the shoulder? We *** in the logs to avoid sensitive values being written to logs and then to disk without people thinking about it. But when they explicitly ran "show me the outputs" I feel like we aren't being helpful.

C. Write in a better option below

I guess at the moment I'm leaning towards A but am looking for other people to say that's OK or give better options. 😀 

---

Option A was selected

---

1. In outputs.go remove the logic to switch out sensitive output values with the path. This is not obvious but an output is considered sensitive when its `WriteOnly` field is true.

https://github.com/deislabs/porter/blob/4401e74fd8933a892d99f9b4244a91efa55e03c2/pkg/porter/outputs.go#L127-L129

2. Update the tests in outputs_test.go to match the changes made.

3. Some of our documentation and text still has the old text in the header "Value (Path if sensitive)". It doesn't appear to be in the actual tables printed by the CLI anymore but let's do a sweep for it and clean up the rest of the repo to be consistent.

4. Good stuff to try after doing this change: 
  * `make build test-unit`
  * ` make install`
  * Use your local install of porter to create a new bundle, define a sensitive output, install it and then list the output

Our [CONTRIBUTING](https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#developer-tasks) explains how to get started with development with Porter but if you have questions, feel free to ask in Slack or here.

**Comment by vdice** [comment]
I'm down w/ A!

**Comment by carolynvs** [comment]
2 votes for option A is enough for me. I've turned this into a Good First Issue if anyone is interested in taking this on as a new contributor!

**Comment by scriptonist** [comment]
Folks, I think I can take this up! @carolynvs

**Comment by carolynvs** [comment]
Great! All yours @scriptonist let me know if you have any questions

**Comment by scriptonist** [comment]
Thanks, @carolynvs :smile: Just wanted to clarify something, Is this normal?
```
╭─atom@drogon /mnt/ships/gowork/src
╰─$ go get -u get.porter.sh/porter                                                                                  (minikube/default)
package get.porter.sh/porter: no Go files in /mnt/ships/gowork/src/get.porter.sh/porter

```

**Comment by carolynvs** [comment]
I usually clone the repository using git since we don't have go files at the root of the repository. You need to be using go 1.13 at this point so it's okay to either put the repo in the GOPATH or clone it outside, whichever you feel more comfortable with.

**Comment by carolynvs** [comment]
But thank you for asking about that. We should update the contributing guide to be more clear on using go get vs git clone. Feel free to submit a PR yourself or I'll get to it eventually. 😀
