### ISSUE TITLE
toml isn't syntax highlighted on our docs site

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#880]
## Describe the bug
Other languages work fine but toml isn't being highlighted for some reason. The proper language tags are being applied but the code in the block is one giant text blob without being broken up by its syntax.

![Screen Shot 2020-02-05 at 3 16 12 PM](https://user-images.githubusercontent.com/1368985/73883943-765f3a00-482a-11ea-8a1d-1154e8ab52fc.png)

![Screen Shot 2020-02-05 at 3 15 30 PM](https://user-images.githubusercontent.com/1368985/73883915-6b0c0e80-482a-11ea-9aeb-b03374b46f7d.png)

 This is something I noticed as I'm adding docs for our new config file, which I'm trying to document as toml. So I can't point to a page on the live doc site yet.

**Comment by carolynvs** [comment]
@flynnduism If you have ideas off the top of your head on where to look, I'd appreciate it. Maybe it's as simple as we need to update our dependencies? 😀

**Comment by flynnduism** [comment]
Looks to me that the site includes [Prism](https://github.com/PrismJS/prism) for syntax highlighting [here](https://porter.sh/src/js/custom/prism.js).
TOML can be added as a supported language, I will PR now
