### ISSUE TITLE
Adding "custom" data to the bundle.json from porter.yaml

### ISSUE THREAD

**Issue by coryodaniel** [deislabs/porter#888]
More of a question or feature request. Is there a way to put information into the `custom` field of bundle.json from `porter.yaml`?

**Comment by carolynvs** [comment]
@coryodaniel Not yet but it would be a very straightforward change to wire up. Getting it into the bundle definition is something we could add for you quickly if you need it, but once there the real question is how to access it inside the bundle.

Were you thinking of reading it back out using the templating, maybe something like `{{ bundle.custom.FOO }}`? Or did you have something else in mind?

**Comment by carolynvs** [comment]
In the meantime, as a workaround you can put this information into a file next to porter.yaml and porter will copy it into the bundle. Then you will have it available for you to read in and use as you need when the bundle is running.

**Comment by coryodaniel** [comment]
I wasn't planning on reading it from porter per-se... 

I was actually planning to abuse the custom field to store some tag/label-like metadata for my own organizational purposes.

Is there another mechanism for adding (not docker) tags/labels to a bundle?

**Comment by carolynvs** [comment]
Oh, if you don't want to read it out and just use it for labels, then you are right, custom is the way to go and Porter should just implement it. I'll add it to the backlog today.

**Comment by carolynvs** [comment]
Here's what we need to support defining custom metadata in the porter.yaml and having it persisted in the bundle.json when the bundle is built:

1. Add a `custom` field of type `map[string]interface{}` to the porter [Manifest](https://github.com/deislabs/porter/blob/master/pkg/manifest/manifest.go#L19) struct
2. In the [ManifestConverter](https://github.com/deislabs/porter/blob/master/pkg/cnab/config-adapter/adapter.go#L59) which is responsible for turning the porter.yaml into the bundle.json, right now we only populate the porter stamp in the `custom` field on the destination. That needs to be expanded to also populate any custom metadata that was defined in the porter.yaml.
3. Add [tests](https://github.com/deislabs/porter/blob/master/pkg/cnab/config-adapter/adapter_test.go) to the ManifestConverter to make sure that your change works both with and without custom metadata defined, and that you cannot overwrite or tamper with the porter stamp entry in Custom.
4. Document how to add custom [metadata](https://github.com/deislabs/porter/blob/master/docs/content/author-bundles.md#bundle-metadata).

**Comment by coryodaniel** [comment]
Nice! Thanks. I'm going through the new contributors guide now!

**Comment by coryodaniel** [comment]
See #894 

* [x] Add a custom field of type map[string]interface{} to the porter Manifest struct
* [x] In the ManifestConverter which is responsible for turning the porter.yaml into the bundle.json, right now we only populate the porter stamp in the custom field on the destination. That needs to be expanded to also populate any custom metadata that was defined in the porter.yaml.
* [x] Add tests to the ManifestConverter to make sure that your change works both with and without custom metadata defined, and that you cannot overwrite or tamper with the porter stamp entry in Custom.
* [x] Document how to add custom metadata.
