### ISSUE TITLE
Support porter credentials edit command

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#890]
Now that credentials are stored in remote places, the cloud! maybe a database!, not always on your file system, we need a command to help people easily locate and edit their credential sets.

```console
$ porter credentials edit NAME
```

* Should read the credential from the plugin system
* Should open the credential using $EDITOR. We may need to be sneaky and save it to a temp file and then have the editor open the temp file. I'm not sure what needs to happen here, so let's look at other tools to see what they do. EDITOR doesn't have to be a text based UI like emacs, nano or vim. It could be VS Code or Notepad.
* I have no idea how to tell when they are done editing it. How does kubectl do this magic? Let's look at other tools again and get inspired. 😀 
* When they are done editing, the credential set should be saved through the plugin system again.

Porter has a field, `Credentials`, that you should use to read and save credentials. This handles the plugin system for you automatically.

https://github.com/deislabs/porter/blob/a533aa84264ccf5cc490df096e72726084fc063d/pkg/credentials/credentialProvider.go#L8-L20

**Comment by halkyon** [comment]
Hey there! I've put an early version of what I think might be what you're after with the edit command: https://github.com/deislabs/porter/pull/921 - before I keep trucking along with it, does this look like what you're after? There's an asciinema recording in the PR description that shows how it works 😄

**Comment by carolynvs** [comment]
This was implemented in #921
