### ISSUE TITLE
Delete unused porter credentials add stub command

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#891]
We stubbed out a command for `porter credentials add` that we decided we won't ever need.

https://github.com/deislabs/porter/blob/a533aa84264ccf5cc490df096e72726084fc063d/cmd/porter/credentials.go#L27-L40

Would some brave soul go in and delete the code and make sure it's all gone?

**Comment by scriptonist** [comment]
@carolynvs I nominate myself to be that brave soul!

**Comment by carolynvs** [comment]
yay!
