### ISSUE TITLE
Remove dead code for "secure" bundles

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#892]
We have code that was added "to be ready for" when secure PKI based bundles were added to the spec. That was in Dec 2018. 😂 

Since then the spec has taken a different direction with bundle security and the stub code we have is both unused (and will need to be changed anyway when the final security spec is ready to implement) and confusing to people. We should remove it for now.

https://github.com/deislabs/porter/blob/f6b5701ed799c2083362b07334a53074f6bd7dde/pkg/cnab/provider/bundle.go#L12-L14

* Remove the `insecure` parameter to the `LoadBundle` function and remove all the logic and variables in the file around signed bundles, such as `ErrNotSigned` and `secflag`.
* Update calling code to not pass in that argument.
* Remove [Insecure](https://github.com/deislabs/porter/blob/master/pkg/cnab/provider/action.go#L27) from ActionArguments, which is passed around a lot through our code and is bound to the [--insecure](https://github.com/deislabs/porter/blob/a533aa84264ccf5cc490df096e72726084fc063d/cmd/porter/bundle.go#L90) flag which we should remove. Make sure to remove examples of `--insecure` from the command examples in /cmd/porter.
* Run `make build` locally to regenerate the website documentation files and include them in your PR.

**Comment by vdice** [comment]
Closed by https://github.com/deislabs/porter/pull/902
