### ISSUE TITLE
Incorporate go tidy into our process

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#996]
I'm starting to see modules that are not used in our code anywhere in our sum file. Let's add go mod tidy to our process, with local commands to start and maybe look for a lightweight, nonintrusive GH action that we could use if we need it.

**Comment by dev-drprasad** [comment]
`go mod tidy` added to makefile by https://github.com/deislabs/porter/pull/1143/files#diff-b67911656ef5d18c4ae36cb6741b7965R50
I think we can close it
